# Copyright (c) 2026 Chrys. All rights reserved.

"""SystemReminderMiddleware — injects ``<system-reminder>`` tags per LLM call.

A ``ChatMiddleware`` that fires before each LLM call in the tool loop.
It replaces the last user message in ``context.messages`` (a per-call
shallow copy) with an enriched version whose original user contents come
first, followed by ``<system-reminder>`` tags (runtime environment,
context usage, profile switch).

Because ``ChatContext.messages`` is a **shallow copy** of the tool loop's
``prepped_messages``, replacing an element in the copy does not affect the
original list.  And ``SessionContext.input_messages`` (used by ``after_run``
for state persistence) is never touched — session state is **automatically
clean** without any restoration logic.

Turn reminders are stable for a logical turn: runtime environment,
previous-turn usage, profile-switch notices, and the runtime skill catalog are
snapshotted at ``prepare_turn()`` and reused for every LLM call in that turn.
User-initiated injection/retry may refresh the skill catalog before the next
model call because a newly added skill is a meaningful runtime capability
change.  LAST_WORDS is different: it is generated by mid-turn compaction and
remains dynamic. Keeping turn reminders stable avoids unnecessary
provider-side cache misses during tool loops; do not reintroduce per-call
timestamps or other volatile reminder text.

Escaping scope: this middleware defangs ``<system-reminder>`` tags in
user-role message content only.  Tool-result content (web fetches, file
reads, sub-agent output) is passed through verbatim — treat reminder-shaped
text in tool results as untrusted in downstream prompts and rely on the
model's own judgement, not on this middleware, to discount it.
"""

from __future__ import annotations

import logging
import sys
from collections.abc import Mapping
from contextvars import ContextVar
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal, cast

from chrys.foundation.platform.files import is_utf8_encodable, surrogate_safe_text
from chrys.foundation.platform.runtime_paths import normalize_path as _normalise_path
from chrys.foundation.platform.runtime_paths import same_path, which_excluding_runtime
from chrys.kernel import Message
from chrys.kernel.middleware import ChatMiddleware
from chrys.service.profiles.models.schema import DEFAULT_MAX_CONTEXT_TOKENS

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable, Sequence

    from chrys.foundation.models.session_env import SessionEnvironment
    from chrys.kernel.middleware import ChatContext
    from chrys.service.context.compaction.spill import SpillQuota

REMINDER_TAG_OPEN = "<system-reminder>"
REMINDER_TAG_CLOSE = "</system-reminder>"
ESCAPED_REMINDER_TAG_OPEN = "&lt;system-reminder&gt;"
ESCAPED_REMINDER_TAG_CLOSE = "&lt;/system-reminder&gt;"

_PYTHON_EXECUTABLE_NAMES = ("python3", "python")
_WINDOWS_PYTHON_EXECUTABLE_NAMES = ("python3", "python", "py")

logger = logging.getLogger(__name__)

_MANIFEST_MAX_LINES = 50
_MANIFEST_MAX_CHARS = 6_000
_MANIFEST_MAX_PERSISTED = 500
_MANIFEST_FIELD_MAX_CHARS = 1_024
_MANIFEST_TOOL_MAX_CHARS = 255
# Catalog-line argument preview caps.  Public because the producer side
# (``compaction.spill._display_argument``) imports them — the constants must
# live here, not in spill: the compaction package ``__init__`` imports this
# module, so the reverse import direction cycles.  Sized to keep whole
# commands, paths, and shell intents visible; the reminder's overall
# char/line budget evicts oldest entries when a long listing overflows, so a
# longer preview trades tail entries, not correctness.
DISPLAY_ARGUMENT_DEFAULT_MAX_CHARS = 120
# Paths middle-truncate (``D:\Repos\…\test.py``) so the filename tail stays.
DISPLAY_ARGUMENT_PATH_MAX_CHARS = 256
# Shell tools append the model-stated ``reason="…"`` after the command.
DISPLAY_ARGUMENT_REASON_MAX_CHARS = 80
# State-field bound = the widest legal display_argument: a lone path segment
# or a command segment plus ", " plus a reason segment.  Derived, so raising
# a per-key cap can never silently re-truncate stored values.
MANIFEST_DISPLAY_ARGUMENT_MAX_CHARS = max(
    DISPLAY_ARGUMENT_PATH_MAX_CHARS,
    DISPLAY_ARGUMENT_DEFAULT_MAX_CHARS + 2 + DISPLAY_ARGUMENT_REASON_MAX_CHARS,
)
_MANIFEST_STATUS_MAX_CHARS = 128
_MANIFEST_STRING_FIELD_LIMITS = {
    "record_id": _MANIFEST_STATUS_MAX_CHARS,
    "group_id": _MANIFEST_FIELD_MAX_CHARS,
    "record_dir": _MANIFEST_FIELD_MAX_CHARS,
    "relative_path": _MANIFEST_FIELD_MAX_CHARS,
    "tool": _MANIFEST_TOOL_MAX_CHARS,
    "display_argument": MANIFEST_DISPLAY_ARGUMENT_MAX_CHARS,
    "outcome": _MANIFEST_STATUS_MAX_CHARS,
    "no_record_reason": _MANIFEST_STATUS_MAX_CHARS,
}
_STATE_INTEGER_MAX = (1 << 63) - 1
_BREAKER_STATE_VERSION = 1
CATALOG_POINTER_RECORD_COUNT_STATE_KEY = "last_words_catalog_pointer_record_count"


@dataclass(frozen=True, slots=True)
class ManifestEntry:
    """One code-generated dropped-call stub stored as JSON-compatible state."""

    record_id: str
    group_id: str
    record_dir: str
    relative_path: str
    turn: int
    round: int
    sequence: int
    tool: str
    display_argument: str
    outcome: str
    size_chars: int
    assistant_text: bool = False
    available: bool = True
    no_record_reason: str = ""

    def to_state(self) -> dict[str, Any]:
        """Return a JSON-compatible representation (never a dataclass instance)."""
        return {
            "record_id": _manifest_state_text(self.record_id, _MANIFEST_STATUS_MAX_CHARS),
            "group_id": _manifest_state_text(self.group_id, _MANIFEST_FIELD_MAX_CHARS),
            "record_dir": _manifest_state_text(self.record_dir, _MANIFEST_FIELD_MAX_CHARS),
            "relative_path": _manifest_state_text(self.relative_path, _MANIFEST_FIELD_MAX_CHARS),
            "turn": self.turn,
            "round": self.round,
            "sequence": self.sequence,
            "tool": _manifest_state_text(self.tool, _MANIFEST_TOOL_MAX_CHARS),
            "display_argument": _manifest_state_text(self.display_argument, MANIFEST_DISPLAY_ARGUMENT_MAX_CHARS),
            "outcome": _manifest_state_text(self.outcome, _MANIFEST_STATUS_MAX_CHARS),
            "size_chars": self.size_chars,
            "assistant_text": self.assistant_text,
            "available": self.available,
            "no_record_reason": _manifest_state_text(self.no_record_reason, _MANIFEST_STATUS_MAX_CHARS),
        }

    @classmethod
    def from_state(cls, value: object) -> ManifestEntry | None:
        """Validate and restore one bounded manifest entry."""
        if not isinstance(value, Mapping):
            logger.debug("Dropping malformed LAST_WORDS manifest entry: expected mapping")
            return None
        strings: dict[str, str] = {}
        for key, limit in _MANIFEST_STRING_FIELD_LIMITS.items():
            item = value.get(key, "")
            if not isinstance(item, str) or len(item) > limit or not is_utf8_encodable(item):
                logger.debug("Dropping malformed LAST_WORDS manifest entry: invalid %s", key)
                return None
            strings[key] = item
        record_dir = Path(strings["record_dir"])
        relative_path = Path(strings["relative_path"]) if strings["relative_path"] else None
        from chrys.service.context.compaction.spill import (
            NOTE_RECORD_GROUP_ID,
            NOTE_RECORD_TOOL_NAME,
            owned_record_directory_relative_path,
            owned_record_relative_path,
        )

        if not strings["group_id"] and strings["tool"] == NOTE_RECORD_TOOL_NAME:
            # Superseded-note entries persisted by the first note-records
            # build carried an empty group_id, which this validator rejects;
            # normalize the legacy shape so those sessions keep their note
            # manifest line instead of silently losing it on restore.
            strings["group_id"] = NOTE_RECORD_GROUP_ID

        if not owned_record_directory_relative_path(record_dir):
            logger.debug("Dropping malformed LAST_WORDS manifest entry: unsafe record_dir")
            return None
        if relative_path is not None and (
            not owned_record_relative_path(relative_path) or relative_path.parent != record_dir
        ):
            logger.debug("Dropping malformed LAST_WORDS manifest entry: unsafe relative_path")
            return None
        integer_fields = ("turn", "round", "sequence", "size_chars")
        integers: dict[str, int] = {}
        for key in integer_fields:
            item = value.get(key)
            if not isinstance(item, int) or isinstance(item, bool) or item < 0 or item > _STATE_INTEGER_MAX:
                logger.debug("Dropping malformed LAST_WORDS manifest entry: invalid %s", key)
                return None
            integers[key] = item
        assistant_text = value.get("assistant_text", False)
        available = value.get("available", True)
        if not isinstance(assistant_text, bool) or not isinstance(available, bool):
            logger.debug("Dropping malformed LAST_WORDS manifest entry: invalid flags")
            return None
        if not strings["group_id"] or not strings["record_dir"] or not strings["tool"]:
            logger.debug("Dropping malformed LAST_WORDS manifest entry: missing required fields")
            return None
        if strings["relative_path"] and not strings["record_id"]:
            logger.debug("Dropping malformed LAST_WORDS manifest entry: path without record id")
            return None
        if not strings["relative_path"] and not strings["no_record_reason"]:
            logger.debug("Dropping malformed LAST_WORDS manifest entry: neither record nor refusal")
            return None
        return cls(
            record_id=strings["record_id"],
            group_id=strings["group_id"],
            record_dir=strings["record_dir"],
            relative_path=strings["relative_path"],
            turn=integers["turn"],
            round=integers["round"],
            sequence=integers["sequence"],
            tool=strings["tool"],
            display_argument=strings["display_argument"],
            outcome=strings["outcome"],
            size_chars=integers["size_chars"],
            assistant_text=assistant_text,
            available=available,
            no_record_reason=strings["no_record_reason"],
        )


@dataclass(frozen=True, slots=True)
class DropRoundBreakerState:
    """Versioned, turn-scoped Phase-4 attempt and spend breaker."""

    version: int = _BREAKER_STATE_VERSION
    attempts: int = 0
    consecutive_no_progress: int = 0
    tail_override: bool = False
    disabled: bool = False
    side_call_tokens: int = 0

    def to_state(self) -> dict[str, Any]:
        """Return the full JSON-compatible breaker state."""
        return {
            "version": self.version,
            "attempts": self.attempts,
            "consecutive_no_progress": self.consecutive_no_progress,
            "tail_override": self.tail_override,
            "disabled": self.disabled,
            "side_call_tokens": self.side_call_tokens,
        }

    @classmethod
    def from_state(cls, value: object) -> DropRoundBreakerState | None:
        """Return a validated breaker state, or ``None`` for old/malformed data."""
        version = value.get("version") if isinstance(value, Mapping) else None
        if (
            not isinstance(value, Mapping)
            or not isinstance(version, int)
            or isinstance(version, bool)
            or version != _BREAKER_STATE_VERSION
        ):
            logger.debug("Dropping malformed or unsupported Phase-4 breaker state")
            return None
        integers: dict[str, int] = {}
        for key in ("attempts", "consecutive_no_progress", "side_call_tokens"):
            item = value.get(key)
            if not isinstance(item, int) or isinstance(item, bool) or item < 0 or item > _STATE_INTEGER_MAX:
                logger.debug("Dropping malformed Phase-4 breaker state: invalid %s", key)
                return None
            integers[key] = item
        tail_override = value.get("tail_override")
        disabled = value.get("disabled")
        if not isinstance(tail_override, bool) or not isinstance(disabled, bool):
            logger.debug("Dropping malformed Phase-4 breaker state: invalid flags")
            return None
        return cls(
            attempts=integers["attempts"],
            consecutive_no_progress=integers["consecutive_no_progress"],
            tail_override=tail_override,
            disabled=disabled,
            side_call_tokens=integers["side_call_tokens"],
        )


@dataclass(frozen=True, slots=True)
class Phase4RetrySnapshot:
    """Attempt-local LAST_WORDS state restored by whole-run retry rollback.

    Breaker accounting and context-pressure delivery are deliberately absent:
    they record real per-turn spend/safety side effects and remain monotonic
    across outer provider retries.  The content-bearing note, its todo
    snapshot, and its active spill manifest instead describe messages dropped
    by one attempt and must roll back with those messages.
    """

    last_words: str | None
    last_words_todo: str | None
    last_words_manifest: tuple[dict[str, Any], ...]


def escape_system_reminder_tags(text: str) -> str:
    """Defang user-authored reminder tags before text reaches the model."""
    return text.replace(REMINDER_TAG_OPEN, ESCAPED_REMINDER_TAG_OPEN).replace(
        REMINDER_TAG_CLOSE,
        ESCAPED_REMINDER_TAG_CLOSE,
    )


def _wrap(content: str) -> str:
    """Wrap *content* in ``<system-reminder>`` tags."""
    return f"{REMINDER_TAG_OPEN}\n{escape_system_reminder_tags(content)}\n{REMINDER_TAG_CLOSE}"


def _format_manifest_size(char_count: int) -> str:
    if char_count < 1_000:
        return str(char_count)
    return f"{char_count / 1_000:.1f}k"


def _manifest_state_text(value: str, max_chars: int) -> str:
    """Return bounded text that strict UTF-8 session persistence can encode."""
    safe = value.encode("utf-8", errors="backslashreplace").decode("utf-8")
    return safe[:max_chars]


@dataclass
class _TurnReminderState:
    """Intentionally mutable reminder state shared across one logical turn.

    ContextVar values are copied into child tasks, so the middleware stores one
    state object and mutates it in place.  That lets Phase 4 LAST_WORDS updates
    made inside an agent child task remain visible to sibling retry/resume tasks
    that continue the same logical turn.
    """

    turn_reminders: tuple[str, ...] = ()
    skill_catalog: str | None = None
    mcp_instructions: str | None = None
    switch: tuple[str, str] | None = None
    file_change: str | None = None
    file_change_delivered: bool = False
    """Whether the notice reached at least one established provider request.

    Set by a ``request_message_observers`` callback at the final-handler
    boundary, not when ``process()`` enriches the messages: on lazy streaming
    paths ``call_next()`` returns a proxy and the request is only established
    at first stream consumption. A pass that ends with this still False
    (Stop, load/hook failure, cancellation before the first request) must
    requeue the notice — the tracker was already drained at ``prepare_turn``.
    """
    last_words: str | None = None
    last_words_todo: str | None = None
    """Todo-list text captured when the LAST_WORDS note was set/restored.

    Captured, never read live: the last-words builder runs on every LLM call,
    so a live provider read would change the request suffix after each
    post-compaction ``todo_write`` — a free-running KV-cache break.  The
    captured text rides the note (same set/refresh/restore/preserve lifecycle).
    """
    last_words_manifest: list[dict[str, Any]] | None = None
    last_words_breaker: dict[str, Any] | None = None
    # Deliberately not part of persisted breaker state: a restored disabled
    # breaker should warn once in the newly resumed process.
    context_pressure_notified: bool = False


@dataclass(frozen=True, eq=False)
class CurrentRunReminderScope:
    """Opaque service-owned token for one logical main-agent run."""

    scope_id: int


@dataclass(frozen=True, eq=False)
class CurrentRunReminderTarget:
    """Opaque service-owned current-run reminder target captured by orchestration."""

    scope: CurrentRunReminderScope
    phase: Literal["pre_prepare", "prepared"]
    generation: int
    state: _TurnReminderState | None = None


@dataclass(frozen=True)
class _PythonExecutionPath:
    """A discovered path relevant to Python execution via a shell tool."""

    label: str
    path: str
    version: str = ""


_PROCESS_SAFE_RUNTIME_PYTHON_BASENAMES = frozenset({"chrys-runtime", "chrys-runtime.exe", "chrys-runtimew.exe"})


class SystemReminderMiddleware(ChatMiddleware):
    """Appends trailing ``<system-reminder>`` content before each LLM call.

    Each LLM call in the tool loop sees a fresh enriched user message
    whose original user contents come first, followed by stable turn-level
    reminders.  Exact reserved reminder tags in user-role text are escaped in
    the per-call ``ChatContext.messages`` copy; tool results are passed through
    unchanged.  ``prepped_messages`` and session state are never modified.
    """

    def __init__(
        self,
        runtime: SessionEnvironment | None = None,
        *,
        max_context_tokens: int = DEFAULT_MAX_CONTEXT_TOKENS,
        warn_threshold_pct: float = 0.50,
        sub_agent_names: list[str] | None = None,
        shell_tool_enabled: bool = False,
        tool_names: list[str] | None = None,
        session_root: Path | None = None,
        file_read_available: bool = False,
        spill_quota: SpillQuota | None = None,
        catalog_pointer_enabled: bool = True,
        skill_catalog_provider: Callable[[], str | None] | None = None,
        todo_state_provider: Callable[[], str | None] | None = None,
        mcp_instructions_provider: Callable[[], str | None] | None = None,
        file_change_provider: Callable[[], str | None] | None = None,
    ) -> None:
        self._runtime = runtime
        self._max_context_tokens = max_context_tokens
        self._warn_threshold_pct = warn_threshold_pct
        self._sub_agent_names = sub_agent_names
        self._shell_tool_enabled = shell_tool_enabled
        self._tool_names = self._dedupe_tool_names(tool_names)
        self._session_root = session_root
        self._file_read_available = file_read_available
        self._spill_quota = spill_quota
        self._catalog_pointer_enabled = catalog_pointer_enabled
        self._catalog_pointer_record_count = 0
        self._catalog_pointer_path: str | None = None
        self._catalog_pointer_snapshot_valid = False
        self._skill_catalog_provider = skill_catalog_provider
        self._todo_state_provider = todo_state_provider
        self._mcp_instructions_provider = mcp_instructions_provider
        self._file_change_provider = file_change_provider
        self._pending_switch: dict[str, str] | None = None
        self._consumed_switch_to: str | None = None
        self._pending_hook_reminders: list[str] = []
        self._next_current_run_scope_id = 1
        self._current_run_scopes: set[CurrentRunReminderScope] = set()
        self._pending_current_run_hook_reminders: dict[CurrentRunReminderScope, list[str]] = {}
        self._active_turn_scope: CurrentRunReminderScope | None = None
        self._current_run_reminder_generation = 0
        state_var_base = f"chrys_system_reminder_{id(self)}"
        self._turn_state: ContextVar[_TurnReminderState | None] = ContextVar(
            f"{state_var_base}_turn_state",
            default=None,
        )
        # Engine lifecycle permits only one active main turn per middleware instance.
        # This fallback lets child/sibling tasks recover the shared state for that turn.
        self._active_turn_state: _TurnReminderState | None = None
        # LAST_WORDS note restored from persisted session state (session
        # resume).  Consumed by the next preserving ``prepare_turn`` so a
        # post-restart retry/continue re-injects the note exactly like an
        # in-process retry; discarded when a fresh turn starts instead.
        self._restored_last_words: str | None = None
        # Todo-list text captured alongside a restored LAST_WORDS note (same
        # single-shot lifecycle as ``_restored_last_words``).
        self._restored_last_words_todo: str | None = None
        self._restored_last_words_manifest: list[dict[str, Any]] | None = None
        self._restored_last_words_breaker: dict[str, Any] | None = None
        self._restored_catalog_pointer_record_count: int | None = None

    def prepare_turn(
        self,
        *,
        reminder_scope: CurrentRunReminderScope | None = None,
        usage: Mapping[str, Any] | None = None,
        preserve_last_words: bool = False,
        preserve_turn_reminders: bool = False,
    ) -> None:
        """Prepare reminder state before ``executor.run()`` or retry/resume.

        ``preserve_last_words`` carries Phase 4 progress across retries.
        ``preserve_turn_reminders`` keeps runtime/usage/switch text
        byte-identical for KV-cache continuity on retry.
        """
        previous = self._current_turn_state()
        snapshot_catalog_pointer = False
        if preserve_turn_reminders and previous is not None:
            turn_reminders = previous.turn_reminders
            skill_catalog = previous.skill_catalog
            mcp_instructions = previous.mcp_instructions
            switch = previous.switch
        else:
            reminders, switch = self._snapshot_turn_reminders(usage=usage or {})
            turn_reminders = tuple(reminders)
            skill_catalog = self._snapshot_skill_catalog()
            mcp_instructions = self._snapshot_mcp_instructions()
            snapshot_catalog_pointer = True
        self._current_run_reminder_generation += 1
        if reminder_scope is not None:
            scoped_reminders = self._pending_current_run_hook_reminders.pop(reminder_scope, [])
            if scoped_reminders:
                turn_reminders = (*turn_reminders, *scoped_reminders)
        if self._pending_hook_reminders:
            turn_reminders = (*turn_reminders, *self._pending_hook_reminders)
            self._pending_hook_reminders.clear()
        last_words: str | None = None
        last_words_todo: str | None = None
        last_words_manifest: list[dict[str, Any]] | None = None
        last_words_breaker: dict[str, Any] | None = None
        context_pressure_notified = False
        if preserve_last_words:
            if previous is not None:
                last_words = previous.last_words
                last_words_todo = previous.last_words_todo
                last_words_manifest = list(previous.last_words_manifest or []) or None
                last_words_breaker = dict(previous.last_words_breaker) if previous.last_words_breaker else None
                context_pressure_notified = previous.context_pressure_notified
            else:
                # Post-restart retry/continue: no in-memory turn state exists,
                # fall back to the key family restored from persisted state.
                last_words = self._restored_last_words
                last_words_todo = self._restored_last_words_todo
                last_words_manifest = list(self._restored_last_words_manifest or []) or None
                last_words_breaker = (
                    dict(self._restored_last_words_breaker) if self._restored_last_words_breaker else None
                )
        if snapshot_catalog_pointer:
            restored_pointer_count = (
                self._restored_catalog_pointer_record_count if preserve_last_words and previous is None else None
            )
            if restored_pointer_count is not None:
                self._set_catalog_pointer_snapshot(restored_pointer_count)
            else:
                # Legacy restored sessions did not persist the turn-start
                # snapshot. Excluding the bounded active manifest is the best
                # compatible approximation, but new saves never rely on it.
                active_manifest_paths = {
                    entry.relative_path
                    for value in last_words_manifest or []
                    if (entry := ManifestEntry.from_state(value)) is not None and entry.relative_path
                }
                self._snapshot_catalog_pointer(excluded_relative_paths=active_manifest_paths)
        # Single-shot either way: a preserving turn consumed it; a fresh turn
        # discards it (matching the in-process new-turn semantics).
        self._restored_last_words = None
        self._restored_last_words_todo = None
        self._restored_last_words_manifest = None
        self._restored_last_words_breaker = None
        self._restored_catalog_pointer_record_count = None
        state = _TurnReminderState(
            turn_reminders=turn_reminders,
            skill_catalog=skill_catalog,
            mcp_instructions=mcp_instructions,
            switch=switch,
            file_change=self._snapshot_file_change(),
            last_words=last_words,
            last_words_todo=last_words_todo,
            last_words_manifest=last_words_manifest,
            last_words_breaker=last_words_breaker,
            context_pressure_notified=context_pressure_notified,
        )
        self._turn_state.set(state)
        self._active_turn_state = state
        self._active_turn_scope = reminder_scope
        self._consumed_switch_to = None

    def take_undelivered_file_change(self) -> str | None:
        """Pop the prepared notice unless a model-bound request already carried it."""
        state = self._current_turn_state()
        if state is None:
            return None
        notice = state.file_change
        state.file_change = None
        if state.file_change_delivered:
            return None
        return notice

    def create_current_run_scope(self) -> CurrentRunReminderScope:
        """Allocate a service-owned reminder scope for a logical main-agent run."""
        scope = CurrentRunReminderScope(self._next_current_run_scope_id)
        self._next_current_run_scope_id += 1
        self._current_run_scopes.add(scope)
        return scope

    def capture_current_run_target(
        self,
        reminder_scope: CurrentRunReminderScope,
    ) -> CurrentRunReminderTarget | None:
        """Capture a current-run reminder target if *reminder_scope* is still valid."""
        if reminder_scope not in self._current_run_scopes:
            return None
        if self._active_turn_scope is reminder_scope and self._active_turn_state is not None:
            return CurrentRunReminderTarget(
                scope=reminder_scope,
                phase="prepared",
                generation=self._current_run_reminder_generation,
                state=self._active_turn_state,
            )
        return CurrentRunReminderTarget(
            scope=reminder_scope,
            phase="pre_prepare",
            generation=self._current_run_reminder_generation,
        )

    def queue_hook_reminders_for_current_run(
        self,
        target: CurrentRunReminderTarget,
        reminders: list[str],
    ) -> bool:
        """Queue hook reminders only if the captured current-run target is still valid."""
        if not self._is_current_run_target_valid(target):
            return False
        clean = [reminder for reminder in reminders if reminder]
        if not clean:
            return True
        if target.phase == "prepared" and target.state is not None:
            target.state.turn_reminders = (*target.state.turn_reminders, *clean)
            return True
        if self._active_turn_scope is target.scope and self._active_turn_state is not None:
            self._active_turn_state.turn_reminders = (*self._active_turn_state.turn_reminders, *clean)
            return True
        self._pending_current_run_hook_reminders.setdefault(target.scope, []).extend(clean)
        return True

    def remove_hook_reminders_for_current_run(
        self,
        target: CurrentRunReminderTarget,
        reminders: list[str],
    ) -> bool:
        """Withdraw queued hook reminders only if the captured target is still valid.

        Mirrors :meth:`queue_hook_reminders_for_current_run` for a mid-run
        injection cancelled after its commit: removes the last occurrence of
        each reminder from wherever it still awaits delivery (the scope's
        pending list or the turn state's reminder tuple), so a withdrawn
        prompt's hook and skill-reference reminders never reach the model.
        """
        if not self._is_current_run_target_valid(target):
            return False
        remaining = [reminder for reminder in reminders if reminder]
        if not remaining:
            return True
        pending = self._pending_current_run_hook_reminders.get(target.scope)
        if pending:
            for reminder in list(remaining):
                for i in range(len(pending) - 1, -1, -1):
                    if pending[i] == reminder:
                        del pending[i]
                        remaining.remove(reminder)
                        break
            if not pending:
                self._pending_current_run_hook_reminders.pop(target.scope, None)
        if not remaining:
            return True
        state = target.state if target.phase == "prepared" else None
        if state is None and self._active_turn_scope is target.scope:
            state = self._active_turn_state
        if state is None:
            return True
        turn_reminders = list(state.turn_reminders)
        for reminder in remaining:
            for i in range(len(turn_reminders) - 1, -1, -1):
                if turn_reminders[i] == reminder:
                    del turn_reminders[i]
                    break
        state.turn_reminders = tuple(turn_reminders)
        return True

    def update_skill_catalog_for_current_run(self, target: CurrentRunReminderTarget) -> bool:
        """Refresh the skill catalog only if the captured current-run target is current."""
        if not self._is_current_run_target_valid(target):
            return False
        if target.phase == "prepared" and target.state is not None:
            target.state.skill_catalog = self._snapshot_skill_catalog()
        elif self._active_turn_scope is target.scope and self._active_turn_state is not None:
            self._active_turn_state.skill_catalog = self._snapshot_skill_catalog()
        return True

    def set_skill_catalog_for_current_run(
        self,
        target: CurrentRunReminderTarget,
        skill_catalog: str | None,
    ) -> bool:
        """Set the skill catalog only if the captured current-run target is current."""
        if not self._is_current_run_target_valid(target):
            return False
        if target.phase == "prepared" and target.state is not None:
            target.state.skill_catalog = skill_catalog
        elif self._active_turn_scope is target.scope and self._active_turn_state is not None:
            self._active_turn_state.skill_catalog = skill_catalog
        return True

    def is_current_run_target_valid(self, target: CurrentRunReminderTarget) -> bool:
        """Return whether a captured current-run reminder target is still valid."""
        return self._is_current_run_target_valid(target)

    def expire_current_run_scope(self, reminder_scope: CurrentRunReminderScope) -> None:
        """Expire a current-run scope and discard stale reminders for it."""
        self._current_run_scopes.discard(reminder_scope)
        self._pending_current_run_hook_reminders.pop(reminder_scope, None)
        if self._active_turn_scope is reminder_scope:
            self._active_turn_scope = None
            self._active_turn_state = None
            self._turn_state.set(None)

    def set_last_words(self, text: str | None) -> None:
        """Set/clear the Phase 4 LAST_WORDS progress note.

        Called by ``UnifiedContextStrategy`` after Phase 4 drops the
        current turn's tool-call history.  The text is appended (as a
        ``<system-reminder>`` block) to the end of the user message's
        content array on every subsequent LLM call until the next turn.

        The current todo-list text is captured here, once, so the dynamic
        block only changes when the note itself changes (set/refresh/restore)
        — never per call.
        """
        state = self._ensure_turn_state()
        state.last_words = text or None
        state.last_words_todo = self._snapshot_todo_state() if state.last_words else None

    def get_last_words(self) -> str | None:
        """Return the current LAST_WORDS text (for incremental regeneration).

        Falls back to a restored-but-not-yet-consumed note so that saving a
        session that was restored and closed again without resuming the turn
        does not erase the persisted note.
        """
        state = self._current_turn_state()
        if state is not None and state.last_words is not None:
            return state.last_words
        return self._restored_last_words

    def append_manifest(self, entries: list[ManifestEntry]) -> None:
        """Append code-generated stubs, retaining the newest persisted entries."""
        if not entries:
            return
        state = self._ensure_turn_state()
        serialized = [*list(state.last_words_manifest or []), *(entry.to_state() for entry in entries)]
        state.last_words_manifest = serialized[-_MANIFEST_MAX_PERSISTED:]

    def mark_manifest_records_unavailable(self, relative_paths: frozenset[str] | set[str]) -> None:
        """Snapshot quota evictions into already-persisted manifest entries."""
        if not relative_paths:
            return
        state = self._ensure_turn_state()
        if not state.last_words_manifest:
            return
        updated: list[dict[str, Any]] = []
        for value in state.last_words_manifest:
            entry = ManifestEntry.from_state(value)
            if entry is None:
                continue
            if entry.relative_path in relative_paths and entry.available:
                entry = replace(entry, available=False)
            updated.append(entry.to_state())
        state.last_words_manifest = updated or None

    def get_last_words_manifest(self) -> list[dict[str, Any]]:
        """Return detached manifest state with current quota evictions applied."""
        state = self._current_turn_state()
        source = state.last_words_manifest if state is not None else self._restored_last_words_manifest
        return self._normalize_active_manifest(source)

    def snapshot_phase4_retry_state(self) -> Phase4RetrySnapshot:
        """Snapshot only the attempt-local, content-bearing Phase-4 state."""
        state = self._ensure_turn_state()
        manifest = self._normalize_active_manifest(state.last_words_manifest)
        return Phase4RetrySnapshot(
            last_words=state.last_words,
            last_words_todo=state.last_words_todo,
            last_words_manifest=tuple(manifest),
        )

    def restore_phase4_retry_state(self, snapshot: Phase4RetrySnapshot) -> None:
        """Restore LAST_WORDS content without rewinding turn-level safety accounting."""
        state = self._ensure_turn_state()
        state.last_words = snapshot.last_words
        # This is the todo text captured when the note was created.  Re-reading
        # the live todo provider here would change the restored note's context.
        state.last_words_todo = snapshot.last_words_todo
        manifest = self._normalize_active_manifest(snapshot.last_words_manifest)
        state.last_words_manifest = manifest or None

    def _normalize_active_manifest(self, source: object) -> list[dict[str, Any]]:
        """Validate manifest rows and synchronize live spill availability."""
        raw = source if isinstance(source, list | tuple) else ()
        entries = [entry for value in raw if (entry := ManifestEntry.from_state(value)) is not None]
        normalized: list[dict[str, Any]] = []
        for entry in entries[-_MANIFEST_MAX_PERSISTED:]:
            if (
                entry.available
                and entry.relative_path
                and self._spill_quota is not None
                and not self._spill_quota.is_record_available(entry.relative_path)
            ):
                entry = replace(entry, available=False)
            normalized.append(entry.to_state())
        return normalized

    def get_drop_round_breaker(self) -> DropRoundBreakerState:
        """Return the active/restored Phase-4 breaker, defaulting empty."""
        state = self._current_turn_state()
        source = state.last_words_breaker if state is not None else self._restored_last_words_breaker
        restored = DropRoundBreakerState.from_state(source) if source is not None else None
        return restored or DropRoundBreakerState()

    def set_drop_round_breaker(self, breaker: DropRoundBreakerState) -> None:
        """Unconditionally replace breaker state, including note-less failures."""
        state = self._ensure_turn_state()
        state.last_words_breaker = breaker.to_state()

    def get_last_words_breaker_state(self) -> dict[str, Any] | None:
        """Return persisted breaker state once Phase 4 has recorded activity."""
        breaker = self.get_drop_round_breaker()
        return breaker.to_state() if breaker != DropRoundBreakerState() else None

    def claim_context_pressure_notification(self) -> bool:
        """Claim the one context-pressure notification allowed per logical turn."""
        state = self._ensure_turn_state()
        if state.context_pressure_notified:
            return False
        state.context_pressure_notified = True
        return True

    def release_context_pressure_notification(self) -> None:
        """Release a failed synchronous notification attempt for a later retry."""
        self._ensure_turn_state().context_pressure_notified = False

    def get_catalog_pointer_record_count_state(self) -> int | None:
        """Return the persisted turn-start catalog count, including zero."""
        if self._catalog_pointer_snapshot_valid:
            return self._catalog_pointer_record_count
        return self._restored_catalog_pointer_record_count

    def refresh_last_words_reminder(self, messages: list[Any]) -> int | None:
        """Rewrite the ``[LAST_WORDS]`` reminder on a per-call message list.

        Phase 4 compaction runs *below* this middleware (inside the client's
        message prep), so the LLM call that triggered it was enriched before
        the new note existed — without this refresh, that call would go out
        with its tool-call history dropped but only a stale note (or none)
        in its place, and the model would restart the task from scratch.

        Rebuilds the last user message with the current note rendered
        exactly as the next call's enrichment will render it, keeping the
        request prefix byte-stable across calls.  The list entry is
        *replaced* with a fresh ``Message`` — the existing object is never
        mutated, because when enrichment was skipped it is the live history
        message.  ``additional_properties`` is shared by reference so
        exclusion flags keep writing through to the history object; the
        caller must recompute any token annotation riding in it, since the
        shared count still describes the pre-refresh contents.  Returns the
        index of the replaced entry, or ``None`` when the list was left
        unmodified.
        """
        message, idx = self._find_user_message(messages)
        if message is None:
            return None
        reminders = self._build_last_words_reminders()
        kept = [c for c in message.contents if not self._is_last_words_reminder_content(c)]
        if len(kept) == len(message.contents) and not reminders:
            return None
        refreshed = Message(message.role, [*kept, *(_wrap(r) for r in reminders)])
        refreshed.additional_properties = message.additional_properties
        messages[idx] = refreshed
        return idx

    @staticmethod
    def _is_last_words_reminder_content(content: Any) -> bool:
        """Whether a content item is a middleware-authored LAST_WORDS reminder.

        User-authored reminder tags are escaped during enrichment, so a raw
        wrapped ``[LAST_WORDS]`` block can only come from
        ``_build_last_words_reminders``.
        """
        return (
            content.type == "text"
            and content.text is not None
            and content.text.startswith(f"{REMINDER_TAG_OPEN}\n[LAST_WORDS] ")
        )

    def restore_last_words(self, text: str | None) -> None:
        """Stash a LAST_WORDS note restored from persisted session state.

        Session restore calls this on a freshly built middleware (no turn
        state exists yet).  The next ``prepare_turn(preserve_last_words=True)``
        — i.e. resuming the interrupted turn — picks the note up so the
        request after restart carries the same ``[LAST_WORDS]`` reminder an
        in-process retry would; starting a fresh turn discards it instead.

        The todo section is re-captured from the (already hydrated) tracker —
        callers must restore ``chrys_todos`` before restoring the note.
        """
        self._restored_last_words = text or None
        self._restored_last_words_todo = self._snapshot_todo_state() if self._restored_last_words else None

    def restore_last_words_manifest(
        self,
        value: object,
        *,
        available_relative_paths: frozenset[str] | set[str] | None = None,
    ) -> None:
        """Validate restored manifest state and snapshot record availability once."""
        if value is not None and not isinstance(value, list):
            logger.debug("Dropping malformed LAST_WORDS manifest state: expected list")
        raw_entries = value if isinstance(value, list) else []
        entries = [entry for item in raw_entries if (entry := ManifestEntry.from_state(item)) is not None]
        entries = entries[-_MANIFEST_MAX_PERSISTED:]
        if available_relative_paths is None:
            available_relative_paths = set()
            if self._session_root is not None:
                from chrys.service.context.compaction.spill import available_record_path

                available_relative_paths = {
                    entry.relative_path
                    for entry in entries
                    if entry.relative_path and available_record_path(self._session_root, entry.relative_path)
                }
        restored: list[dict[str, Any]] = []
        for entry in entries:
            available = not entry.relative_path or entry.relative_path in available_relative_paths
            restored.append(
                ManifestEntry(
                    record_id=entry.record_id,
                    group_id=entry.group_id,
                    record_dir=entry.record_dir,
                    relative_path=entry.relative_path,
                    turn=entry.turn,
                    round=entry.round,
                    sequence=entry.sequence,
                    tool=entry.tool,
                    display_argument=entry.display_argument,
                    outcome=entry.outcome,
                    size_chars=entry.size_chars,
                    assistant_text=entry.assistant_text,
                    available=entry.available and available,
                    no_record_reason=entry.no_record_reason,
                ).to_state()
            )
        self._restored_last_words_manifest = restored or None

    def restore_last_words_breaker(self, value: object) -> None:
        """Stash validated breaker state for the next preserving prepare."""
        breaker = DropRoundBreakerState.from_state(value)
        self._restored_last_words_breaker = breaker.to_state() if breaker is not None else None

    def restore_catalog_pointer_record_count(self, value: object) -> None:
        """Stash a validated turn-start catalog count for a restored retry."""
        if value is None:
            self._restored_catalog_pointer_record_count = None
            return
        if not isinstance(value, int) or isinstance(value, bool) or value < 0 or value > _STATE_INTEGER_MAX:
            logger.debug("Dropping malformed dropped-record catalog pointer count")
            self._restored_catalog_pointer_record_count = None
            return
        self._restored_catalog_pointer_record_count = value

    def restore_phase4_state(
        self,
        state: Mapping[str, Any] | None,
        *,
        available_relative_paths: frozenset[str] | set[str] | None = None,
    ) -> None:
        """Re-arm the persisted Phase-4 state family after a runtime rebuild."""
        state = state or {}
        self.restore_last_words(state.get("last_words"))
        self.restore_last_words_manifest(
            state.get("last_words_manifest"),
            available_relative_paths=available_relative_paths,
        )
        self.restore_last_words_breaker(state.get("last_words_breaker"))
        self.restore_catalog_pointer_record_count(state.get(CATALOG_POINTER_RECORD_COUNT_STATE_KEY))

    def queue_hook_reminders(self, reminders: list[str], *, for_next_turn: bool = False) -> None:
        """Queue hook-provided reminders for the current or next user turn."""
        clean = [r for r in reminders if r]
        if not clean:
            return
        state = None if for_next_turn else self._current_turn_state()
        if state is not None:
            state.turn_reminders = (*state.turn_reminders, *clean)
            return
        self._pending_hook_reminders.extend(clean)

    def update_skill_catalog_for_active_turn(self) -> None:
        """Refresh the active turn's skill-catalog reminder from the provider."""
        state = self._current_turn_state()
        if state is None:
            return
        state.skill_catalog = self._snapshot_skill_catalog()

    def set_profile_switch(self, from_label: str, to_label: str) -> None:
        """Set pending profile switch info."""
        self._pending_switch = {"from": from_label, "to": to_label}

    def update_profile_switch_to(self, to_label: str) -> None:
        """Update *to* for consecutive switches (keep original *from*)."""
        if self._pending_switch is not None:
            self._pending_switch["to"] = to_label

    @property
    def has_pending_switch(self) -> bool:
        return self._pending_switch is not None

    def snapshot_pending_switch(self) -> dict[str, str] | None:
        """Return a copy of pending profile-switch metadata, if any."""
        return self._pending_switch.copy() if self._pending_switch is not None else None

    @property
    def consumed_switch_to(self) -> str | None:
        """The display name we switched to, if consumed this turn."""
        return self._consumed_switch_to

    # ------------------------------------------------------------------
    # ChatMiddleware interface
    # ------------------------------------------------------------------

    async def process(
        self,
        context: ChatContext,
        call_next: Callable[[], Awaitable[None]],
    ) -> None:
        turn_reminders = self._build_reminders()
        last_words_reminders = self._build_last_words_reminders()
        applied_switch: tuple[str, str] | None = None
        # Replace user messages in the per-call shallow copy only.  This
        # defangs user-authored reminder tags without modifying the tool loop's
        # prepped_messages or SessionContext.input_messages.  Tool-result
        # messages are intentionally not escaped here.
        # ``ChatMiddlewareLayer`` always gives ``ChatContext`` a fresh mutable
        # list; the kernel constructor's public annotation is the broader
        # ``Sequence`` accepted at its external boundary.
        messages = cast("list[Message]", context.messages)
        _, last_user_idx = self._find_user_message(messages)
        for msg_idx, message in enumerate(messages):
            if message.role != "user":
                continue
            message_turn_reminders = turn_reminders if msg_idx == last_user_idx else []
            message_last_words_reminders = last_words_reminders if msg_idx == last_user_idx else []
            if message_turn_reminders or message_last_words_reminders or self._has_system_reminder_tags(message):
                messages[msg_idx] = self._create_enriched(
                    message,
                    message_turn_reminders,
                    message_last_words_reminders,
                )
                if msg_idx == last_user_idx:
                    state = self._current_turn_state()
                    if state is not None and state.file_change:
                        # Delivered means an established provider request, not
                        # a completed middleware chain: lazy streaming inner
                        # middleware returns a proxy from call_next() and only
                        # reaches the final handler at first stream
                        # consumption. Observers run immediately before every
                        # final-handler invocation, so a run cancelled before
                        # consumption keeps the notice requeueable.
                        def _mark_file_change_delivered(
                            _messages: Sequence[Message],
                            _state: _TurnReminderState = state,
                        ) -> None:
                            _state.file_change_delivered = True

                        context.request_message_observers.append(_mark_file_change_delivered)
                    switch = state.switch if state is not None else None
                    if switch is not None:
                        applied_switch = switch

        await call_next()
        if applied_switch is not None:
            self._consumed_switch_to = applied_switch[1]
            pending = self._pending_switch
            if (
                pending is not None
                and pending.get("from") == applied_switch[0]
                and pending.get("to") == applied_switch[1]
            ):
                self._pending_switch = None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_reminders(self) -> list[str]:
        state = self._turn_state.get()
        if state is None:
            # Fallback for direct middleware use without ``prepare_turn()``.
            # It deliberately avoids consuming pending profile switches:
            # switch reminders are turn-scoped and must be snapshotted by
            # the caller that starts the turn.
            reminders, switch = self._snapshot_turn_reminders(usage={}, include_pending_switch=False)
            state = _TurnReminderState(
                turn_reminders=tuple(reminders),
                skill_catalog=self._snapshot_skill_catalog(),
                mcp_instructions=self._snapshot_mcp_instructions(),
                switch=switch,
            )
            self._turn_state.set(state)
        reminders = list(state.turn_reminders)
        if state.file_change:
            reminders.append(state.file_change)
        if state.skill_catalog:
            reminders.append(state.skill_catalog)
        if state.mcp_instructions:
            reminders.append(state.mcp_instructions)
        if self._catalog_pointer_record_count and self._catalog_pointer_path:
            record_label = "record" if self._catalog_pointer_record_count == 1 else "records"
            reminders.append(
                "Earlier context compaction archived "
                f"{self._catalog_pointer_record_count} {record_label} from previous turns; "
                f"catalog: {self._catalog_pointer_path} (contains each record's relative path)."
            )
        return reminders

    def _snapshot_file_change(self) -> str | None:
        """Drain the advisory provider without allowing it to break a turn."""
        if self._file_change_provider is None:
            return None
        try:
            return self._file_change_provider() or None
        except Exception:
            logger.debug("Workspace file-change reminder provider failed", exc_info=True)
            return None

    def _snapshot_catalog_pointer(self, *, excluded_relative_paths: set[str] | None = None) -> None:
        """Capture the catalog count/path at a real turn boundary."""
        if not self._catalog_pointer_enabled or self._session_root is None or self._spill_quota is None:
            self._set_catalog_pointer_snapshot(0)
            return
        record_count = self._spill_quota.live_record_count(
            excluded_relative_paths=excluded_relative_paths or (),
        )
        self._set_catalog_pointer_snapshot(record_count)

    def _set_catalog_pointer_snapshot(self, record_count: int) -> None:
        """Install one stable turn-start count and derive its read affordance."""
        self._catalog_pointer_record_count = record_count
        self._catalog_pointer_path = None
        self._catalog_pointer_snapshot_valid = True
        if (
            record_count
            and self._catalog_pointer_enabled
            and self._file_read_available
            and self._session_root is not None
            and self._spill_quota is not None
            and self._spill_quota.storage_available
        ):
            from chrys.service.context.compaction.spill import catalog_path_for_read

            catalog = catalog_path_for_read(self._session_root)
            if catalog is not None:
                self._catalog_pointer_path = catalog.absolute().as_posix()

    def _snapshot_skill_catalog(self) -> str | None:
        """Return the latest runtime skill catalog, if a provider is configured."""
        if self._skill_catalog_provider is None:
            return None
        try:
            return self._skill_catalog_provider()
        except Exception:
            logger.exception("Failed to render runtime skill catalog reminder")
            return None

    def _snapshot_mcp_instructions(self) -> str | None:
        """Return the current MCP server instructions block, if a provider is configured."""
        if self._mcp_instructions_provider is None:
            return None
        try:
            return self._mcp_instructions_provider()
        except Exception:
            logger.exception("Failed to render MCP server instructions reminder")
            return None

    def _snapshot_todo_state(self) -> str | None:
        """Return the current todo-list reminder text, if a provider is configured."""
        if self._todo_state_provider is None:
            return None
        try:
            return self._todo_state_provider()
        except Exception:
            logger.exception("Failed to render todo-list reminder")
            return None

    def _current_turn_state(self) -> _TurnReminderState | None:
        """Return context-local turn state, falling back to the active logical turn."""
        return self._turn_state.get() or self._active_turn_state

    def _is_current_run_target_valid(self, target: CurrentRunReminderTarget) -> bool:
        if target.scope not in self._current_run_scopes:
            return False
        if target.phase == "prepared":
            return self._active_turn_scope is target.scope and self._active_turn_state is target.state
        if self._active_turn_scope is target.scope and self._active_turn_state is not None:
            return True
        return self._active_turn_scope is None and target.generation == self._current_run_reminder_generation

    def _ensure_turn_state(self) -> _TurnReminderState:
        """Return existing turn state or create fallback state for direct calls."""
        state = self._current_turn_state()
        if state is None:
            state = _TurnReminderState()
            self._turn_state.set(state)
        return state

    def _snapshot_turn_reminders(
        self,
        *,
        usage: Mapping[str, Any],
        include_pending_switch: bool = True,
    ) -> tuple[list[str], tuple[str, str] | None]:
        """Build stable turn-level reminders, optionally including a pending switch."""
        from chrys.service.context.middleware.usage import format_usage_hint

        reminders: list[str] = []
        switch: tuple[str, str] | None = None

        # 1. Runtime environment (cwd, shell, time at turn start)
        if self._runtime is not None:
            reminders.append(self._format_runtime_hint())

        # 2. Context usage from previous turn
        if usage:
            hint = format_usage_hint(
                usage,
                max_context_tokens=self._max_context_tokens,
                warn_threshold_pct=self._warn_threshold_pct,
                sub_agent_names=self._sub_agent_names,
            )
            reminders.append(hint)

        # 3. Profile switch (stable for this turn)
        if include_pending_switch and self._pending_switch is not None:
            ps = self._pending_switch
            reminders.append(self._format_profile_switch_hint(ps["from"], ps["to"]))
            switch = (ps["from"], ps["to"])

        # 4. Session todo list (turn-start snapshot; empty list → no reminder)
        todo_state = self._snapshot_todo_state()
        if todo_state:
            reminders.append(todo_state)

        return reminders, switch

    @staticmethod
    def _dedupe_tool_names(tool_names: list[str] | None) -> tuple[str, ...]:
        """Return non-empty tool names in caller order, without duplicates."""
        if not tool_names:
            return ()
        names: list[str] = []
        seen: set[str] = set()
        for name in tool_names:
            clean = name.strip()
            if clean and clean not in seen:
                names.append(clean)
                seen.add(clean)
        return tuple(names)

    def _format_profile_switch_hint(self, from_label: str, to_label: str) -> str:
        """Format the profile-switch reminder shown to the new agent."""
        if self._tool_names:
            tools = ", ".join(self._tool_names)
            tool_hint = f"Your currently available tools are: {tools}."
        else:
            tool_hint = "Your current agent has no available tools."
        return (
            f"[Agent profile switched from '{from_label}' to '{to_label}']\n"
            "System instructions may also have changed; read and follow your current instructions carefully. "
            "Earlier conversation may include tool-call records created by the previous agent. "
            f"{tool_hint} You may only use tools that are currently available to you; "
            "treat earlier tool calls as reference and context only."
        )

    def render_last_words_reminder_text(self) -> str | None:
        """Render the LAST_WORDS reminder exactly as the next model call injects it.

        Public debug-oriented view over ``_build_last_words_reminders`` for
        callers (the compaction strategy) that want to persist the injected
        text without reimplementing the rendering.  Each block carries the
        same ``<system-reminder>`` envelope and tag-escaping the enrichment
        path applies, so the dump matches the wire prompt (on the wire the
        blocks are separate content items of one message; here they join
        with a blank line).  ``None`` when no LAST_WORDS state exists and
        nothing would be injected.
        """
        reminders = self._build_last_words_reminders()
        if not reminders:
            return None
        return "\n\n".join(_wrap(reminder) for reminder in reminders)

    def _build_last_words_reminders(self) -> list[str]:
        """Build dynamic reminders that attach after the user message content.

        A filesystem-free function of stored turn state plus the shared
        in-memory spill ledger: the todo section is the text captured at
        set/restore time, rendered INSIDE the ``[LAST_WORDS]``-prefixed string
        (``refresh_last_words_reminder`` strips only ``[LAST_WORDS]``-prefixed
        contents — a separately wrapped block would accumulate stale copies
        across refreshes).
        """
        reminders: list[str] = []
        last_words = self.get_last_words()
        manifest = self._current_manifest_entries()
        if last_words or manifest:
            # Task-anchored wording (§5.4): the reminder rides the LAST user
            # message, which on an injected turn is an injection or a
            # synthetic ``continue`` — "the above request" would anchor the
            # agent on the wrong message.  The ``[LAST_WORDS] `` prefix is
            # load-bearing (``_is_last_words_reminder_content`` strips by
            # prefix match during refresh); keep it byte-identical.
            text = (
                "[LAST_WORDS] You previously made progress on the current task "
                "(the user's request and any follow-up messages above) but ran "
                "out of context, so your earlier tool-call history for this "
                "task has been dropped.  The note below is your own updated progress "
                "record — read it and resume from where you left off.  Do NOT redo "
                "work that the note says is already done.  If the note says the "
                "work is finished but you have not yet delivered the final reply "
                "to the user, do not re-gather anything — compose and deliver "
                "that reply now from the note."
            )
            if last_words:
                text += "\n\n" + last_words.strip()
            todo_section = self._current_last_words_todo()
            if todo_section:
                text += "\n\n" + todo_section
            if manifest:
                text += "\n\n" + self._render_manifest(manifest)
            reminders.append(text)
        return reminders

    def _current_manifest_entries(self) -> list[ManifestEntry]:
        """Restore validated dataclasses from the JSON-only turn state."""
        return [
            entry for value in self.get_last_words_manifest() if (entry := ManifestEntry.from_state(value)) is not None
        ]

    def _render_manifest(self, entries: list[ManifestEntry]) -> str:
        """Render the bounded dropped-call appendix without filesystem access."""
        record_dir = entries[-1].record_dir
        absolute_dir = (
            (self._session_root / record_dir).absolute().as_posix() if self._session_root is not None else record_dir
        )
        heading = f"--- Dropped this turn (records under {absolute_dir.rstrip('/')}/) ---"
        rendered_entries = [self._render_manifest_entry(entry) for entry in entries]
        omitted = 0

        affordance = (
            "To inspect archived input/output, read the listed file with read_file; "
            "capped records contain an explicit middle-truncation marker."
            if self._file_read_available and any(entry.available and entry.relative_path for entry in entries)
            else ""
        )

        def _compose() -> str:
            lines = [heading]
            if omitted:
                lines.append(f"… and {omitted} earlier records — see manifest.md")
            lines.extend(rendered_entries)
            if affordance:
                lines.append(affordance)
            return "\n".join(lines)

        rendered = _compose()
        while (
            len(rendered) > _MANIFEST_MAX_CHARS or len(rendered.splitlines()) > _MANIFEST_MAX_LINES
        ) and rendered_entries:
            rendered_entries.pop(0)
            omitted += 1
            rendered = _compose()
        if len(rendered) > _MANIFEST_MAX_CHARS:
            rendered = rendered[: _MANIFEST_MAX_CHARS - 1] + "…"
        return rendered

    @staticmethod
    def _render_manifest_entry(entry: ManifestEntry) -> str:
        size = _format_manifest_size(entry.size_chars)
        if entry.assistant_text:
            body = f"r{entry.round} {entry.sequence:03d} assistant text, {size} chars"
        else:
            argument = f"{entry.display_argument}" if entry.display_argument else "…"
            body = f"r{entry.round} {entry.sequence:03d} {entry.tool}({argument}) → {entry.outcome}, {size} chars"
        if entry.no_record_reason:
            return f"{body} — (no record: {entry.no_record_reason})"
        filename = Path(entry.relative_path).name
        suffix = f" — {filename}"
        if not entry.available:
            suffix += " (record missing)"
        return body + suffix

    def _current_last_words_todo(self) -> str | None:
        """Todo text captured with the active LAST_WORDS note, if any."""
        state = self._current_turn_state()
        if state is not None and state.last_words is not None:
            return state.last_words_todo
        return self._restored_last_words_todo

    def _format_runtime_hint(self) -> str:
        """Format runtime info for the current moment; callers cache it at turn start."""
        rt = self._runtime
        if rt is None:
            return ""

        now_utc = datetime.now(tz=UTC)
        now_local = now_utc.astimezone()

        shell = rt.platform.shell
        shell_line = f"  Shell: {shell.name} {shell.version} ({shell.path})".rstrip()
        lines = [
            "[Runtime Environment]",
            f"  Working directory: {rt.cwd}",
            f"  OS: {rt.platform.os_name} ({rt.platform.arch})",
            shell_line,
        ]
        lines.extend(
            f"  Shell: {extra.name} {extra.version} ({extra.path})".rstrip() for extra in rt.platform.extra_shells
        )
        if self._shell_tool_enabled:
            lines.extend(_format_python_execution_paths_hint())
        lines.extend(
            [
                f"  Local time: {now_local.strftime('%Y-%m-%d %H:%M:%S %Z')}",
                f"  UTC time: {now_utc.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            ]
        )
        if rt.working_dirs:
            lines.append("  Working directories:")
            for wd in rt.working_dirs:
                marker = " (primary)" if wd.is_primary else ""
                label = f" [{wd.label}]" if wd.label else ""
                lines.append(f"    - {wd.path}{label}{marker}")
        return surrogate_safe_text("\n".join(lines))

    @staticmethod
    def _find_user_message(messages: list[Any]) -> tuple[Message | None, int]:
        """Return the last user ``Message`` and its index, or ``(None, -1)``."""
        for i in range(len(messages) - 1, -1, -1):
            if messages[i].role == "user":
                return messages[i], i
        return None, -1

    @staticmethod
    def _has_system_reminder_tags(message: Message) -> bool:
        """Return true if a message contains raw reserved reminder tags."""
        for c in message.contents:
            if (
                c.type == "text"
                and c.text is not None
                and (REMINDER_TAG_OPEN in c.text or REMINDER_TAG_CLOSE in c.text)
            ):
                return True
        return False

    @staticmethod
    def _create_enriched(
        original: Message,
        turn_reminders: list[str],
        last_words_reminders: list[str],
    ) -> Message:
        """Create a new ``Message`` with user contents first and reminders last.

        This keeps the user's message as the first content item while leaving
        platform context close to the end of the message.
        """
        reminder_contents = [_wrap(r) for r in [*turn_reminders, *last_words_reminders]]
        # Extract text from Content objects so Message() can rebuild them.
        # Non-text Content (images, etc.) is passed through as-is.
        original_items: list[Any] = []
        for c in original.contents:
            if c.type == "text" and c.text is not None:
                original_items.append(escape_system_reminder_tags(c.text))
            else:
                original_items.append(c)
        enriched = Message(
            original.role,
            [*original_items, *reminder_contents],
        )
        enriched.additional_properties = original.additional_properties
        return enriched


def _format_python_execution_paths_hint() -> list[str]:
    """Format Python execution paths for agents that can use a shell tool."""
    paths = _python_execution_paths()
    if not paths:
        return []

    has_runtime_python = any(path.label == "your runtime Python" for path in paths)
    has_system_uv = any(path.label == "system uv" for path in paths)
    lines = ["  Python execution paths (for Python scripts or Python commands):"]
    lines.extend(_format_python_execution_path_line(path) for path in paths)
    if has_system_uv:
        lines.append(
            "  Consider uv or uvx for ad-hoc Python scripts/tools with temporary dependencies to avoid modifying "
            "user system or project Python environments, unless user/project/skill instructions say otherwise."
        )
    if has_runtime_python:
        lines.append(
            "  Your runtime Python path is a fallback for Python scripts/commands when no suitable system uv or "
            "Python executable is available."
        )
        if not _runtime_python_uses_process_safe_alias():
            lines.append(
                "  Avoid broad Python-process termination commands (for example Get-Process python | Stop-Process, "
                "pkill python, or killall python); they may terminate your own runtime. Target specific PIDs or child "
                "processes you started."
            )
    return lines


def _runtime_python_uses_process_safe_alias() -> bool:
    """Return true when the runtime executable basename is Chrys' PyApp alias."""
    basename = sys.executable.replace("\\", "/").rsplit("/", 1)[-1].casefold()
    return basename in _PROCESS_SAFE_RUNTIME_PYTHON_BASENAMES


def _python_execution_paths() -> list[_PythonExecutionPath]:
    """Return available Python execution paths in stable discovery order."""
    runtime_python = _normalise_path(sys.executable)

    paths: list[_PythonExecutionPath] = []
    system_uv = which_excluding_runtime("uv", frozen_only=False, fallback_to_runtime=False)
    if system_uv:
        _append_python_execution_path(paths, _python_execution_path("system uv", system_uv))

    system_python = _first_executable(
        _python_executable_names(),
        exclude_paths=(runtime_python,),
    )
    if system_python:
        _append_python_execution_path(
            paths,
            _python_execution_path("system Python", system_python),
        )

    if runtime_python:
        _append_python_execution_path(
            paths,
            _python_execution_path("your runtime Python", runtime_python, version=_runtime_python_version()),
        )

    return paths


def _format_python_execution_path_line(path: _PythonExecutionPath) -> str:
    version = f" ({path.version})" if path.version else ""
    return f"    - {path.label}{version}: {path.path}"


def _append_python_execution_path(paths: list[_PythonExecutionPath], new_path: _PythonExecutionPath) -> None:
    """Append *new_path*, merging labels when the same executable is already listed."""
    for index, existing in enumerate(paths):
        if same_path(existing.path, new_path.path):
            labels = [*existing.label.split(" / "), new_path.label]
            version = existing.version or new_path.version
            paths[index] = _PythonExecutionPath(
                label=" / ".join(dict.fromkeys(labels)),
                path=existing.path,
                version=version,
            )
            return
    paths.append(new_path)


def _python_execution_path(label: str, path: str, *, version: str = "") -> _PythonExecutionPath:
    return _PythonExecutionPath(label=label, path=path, version=version)


def _runtime_python_version() -> str:
    version = sys.version_info
    return f"{version.major}.{version.minor}.{version.micro}"


def _python_executable_names() -> tuple[str, ...]:
    """Return executable names that should be treated as Python on this platform."""
    if sys.platform == "win32":
        return _WINDOWS_PYTHON_EXECUTABLE_NAMES
    return _PYTHON_EXECUTABLE_NAMES


def _first_executable(
    names: tuple[str, ...],
    *,
    exclude_paths: tuple[str, ...] = (),
) -> str:
    """Return the first executable found on PATH."""
    for name in names:
        path = which_excluding_runtime(
            name,
            frozen_only=False,
            fallback_to_runtime=False,
            exclude_paths=exclude_paths,
        )
        if path:
            return path
    return ""
