# Copyright (c) 2026 Chrys. All rights reserved.

"""Ports the settings dialog talks through; the main screen implements them."""

from __future__ import annotations

from collections.abc import Awaitable, Callable, Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from chrys.app.tui.notifications.settings import NotificationSettings
    from chrys.app.tui.screens.settings.layout import Suggestions
    from chrys.foundation.config.settings_store import LoadedSettings
    from chrys.foundation.config.spec import ChoiceProvider
    from chrys.foundation.i18n import MessageRef
    from chrys.service.state.session_migration import MigrationPlan, MigrationReport


class NotificationPorts(Protocol):
    """What the notifications pane needs: the live settings and its two callbacks."""

    def current(self) -> NotificationSettings: ...
    def save(self, settings: NotificationSettings) -> bool: ...
    def test(self, settings: NotificationSettings) -> Awaitable[bool]: ...


class SessionStoragePorts(Protocol):
    """Session-root validation and the migration service, disk work included."""

    def in_force_sessions_dir(self) -> Path: ...
    def default_sessions_dir(self) -> Path: ...
    def probe_root(self, raw: str) -> Path | None: ...
    def plan_migration(self, source: Path, destination: Path) -> MigrationPlan: ...
    def run_migration(self, plan: MigrationPlan) -> Awaitable[MigrationReport]: ...


class SettingsPanelPorts(Protocol):
    """Everything the settings dialog may ask of the screen that opened it."""

    @property
    def loaded(self) -> LoadedSettings: ...
    def resolve_choices(self, source: ChoiceProvider | Suggestions) -> Sequence[tuple[str, str]]: ...
    def schedule_persist(self, values: Mapping[str, Any]) -> None: ...
    def apply_live(self, key: str, value: Any) -> None: ...
    def projected_value(self, key: str) -> Any: ...
    def restart_pending_keys(self) -> frozenset[str]: ...
    def reload_dirty(self) -> bool: ...
    def turn_in_progress(self) -> bool: ...
    def on_dialog_closed(self) -> None: ...
    def notifications(self) -> NotificationPorts: ...
    def session_storage(self) -> SessionStoragePorts: ...

    def confirm(self, message: MessageRef, on_result: Callable[[bool], None]) -> None: ...
    def notify_error(self, message: MessageRef) -> None: ...
