# Copyright (c) 2026 Chrys. All rights reserved.
# Adapted from toad (https://github.com/batrachianai/toad).

CONTROL_CODES = {
    "D": "ind",
    "E": "nel",
    "H": "hts",
    "I": "htj",
    "J": "vts",
    "K": "pld",
    "L": "plu",
    "M": "ri",
    "N": "ss2",
    "O": "ss3",
    "P": "dcs",
    "Q": "pu1",
    "R": "pu2",
    "S": "sts",
    "T": "cch",
    "U": "mw",
    "V": "spa",
    "W": "epa",
    "X": "sos",
    "Z": "decid",
    "[": "csi",
    "\\": "st",
    "]": "osc",
    "^": "pm",
    "_": "apc",
    "c": "ris",
    "7": "decsc",
    "8": "decrc",
    "=": "deckpam",
    ">": "deckpnm",
    "#": "decaln",
    "(": "scs_g0",
    ")": "scs_g1",
    "*": "scs_g2",
    "+": "scs_g3",
}
