#!/usr/bin/env python3
"""Mine repository facts for semantic-search Augmented Requirement generation."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

from _common import (
    FORMAT_FACTS,
    FORMAT_GLOBAL,
    FORMAT_INDEX,
    FORMAT_REPOSITORY,
    ScriptError,
    append_trace,
    bullet_lines,
    ensure_allowed_path,
    load_json,
    now_iso,
    path_tokens,
    read_text,
    reject_benchmark_answer_path,
    resolve_path,
    sha1_path,
    stable_unique,
    tokenize,
    write_json,
)

SURFACE_RULES = {
    "syntax-parser": {
        "terms": {"grammar", "parser", "parse", "syntax", "token", "lexer", "expression", "statement", "keyword"},
        "path_terms": {"grammar", "parser", "token"},
        "risk": "Syntax and parser work often requires source-of-truth grammar/token files and generated artifacts to stay in sync.",
    },
    "compiler-runtime": {
        "terms": {
            "compiler",
            "compile",
            "runtime",
            "bytecode",
            "opcode",
            "interpreter",
            "scope",
            "semantic",
            "execution",
        },
        "path_terms": {"python", "objects", "runtime", "compiler", "opcode"},
        "risk": "Runtime changes can pass local examples while breaking existing behavior or introspection paths.",
    },
    "library-api": {
        "terms": {"api", "class", "function", "method", "module", "library", "public", "typing", "alias"},
        "path_terms": {"lib", "src", "main"},
        "risk": "Public API changes may require exports, docs, introspection behavior, and compatibility checks.",
    },
    "cli-config": {
        "terms": {"cli", "command", "flag", "option", "config", "configuration", "setting", "argument"},
        "path_terms": {"cli", "config", "cmd", "command", "settings"},
        "risk": "CLI/config changes often need parsing, validation, defaults, and help or docs updates.",
    },
    "build-generated": {
        "terms": {"generated", "generate", "build", "regenerate", "autogenerated", "codegen"},
        "path_terms": {"build", "generated", "tools", "scripts"},
        "risk": "Generated or registered artifacts can make a logically correct source edit fail at build time.",
    },
    "tests-validation": {
        "terms": {"test", "tests", "testing", "validate", "failure", "error", "expected"},
        "path_terms": {"test", "tests"},
        "risk": "Feature work should be checked against narrow tests and P2P-sensitive existing tests.",
    },
}


COMMON_PATH_TOKENS = {
    "android",
    "app",
    "build",
    "common",
    "config",
    "core",
    "doc",
    "docs",
    "file",
    "files",
    "java",
    "lib",
    "library",
    "main",
    "module",
    "org",
    "python",
    "src",
    "test",
    "tests",
    "tool",
    "tools",
}

GENERIC_VALIDATION_TOKENS = COMMON_PATH_TOKENS | {
    "arg",
    "args",
    "bytes",
    "data",
    "dir",
    "error",
    "errors",
    "file",
    "init",
    "init__.py",
    "key",
    "name",
    "names",
    "object",
    "objects",
    "parameter",
    "parameters",
    "repr",
    "support",
    "unicode",
    "value",
    "values",
}

IMPORTANT_BUILD_NAMES = {
    "configure",
    "configure.ac",
    "Makefile",
    "Makefile.pre.in",
    "meson.build",
    "pom.xml",
    "pyproject.toml",
    "setup.py",
}


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True, help="Seeded workspace repo root.")
    parser.add_argument("--requirement", required=True, help="Original task prompt or instruction file.")
    parser.add_argument("--index", required=True, help="Light semantic-search index from build_index.py.")
    parser.add_argument("--out", required=True, help="Output code-facts.json path.")
    parser.add_argument("--artifact-dir", help="Semantic-search artifact directory. Defaults to output parent.")
    parser.add_argument("--global-perception", help="Optional global-perception.json from global_perception.py.")
    parser.add_argument(
        "--repository-perception", help="Optional repository-perception.json from repository_perception.py."
    )
    parser.add_argument(
        "--semantic-out",
        help="Output semantic-perception.json path. Defaults to artifact-dir/semantic-perception.json.",
    )
    parser.add_argument(
        "--semantic-markdown",
        help="Output semantic-perception.md path. Defaults to artifact-dir/semantic-perception.md.",
    )
    parser.add_argument("--top-files", type=int, default=18)
    parser.add_argument("--top-symbols", type=int, default=24)
    return parser.parse_args(argv)


def load_inputs(
    args: argparse.Namespace,
) -> tuple[Path, Path, Path, Path, Path, Path, Path, str, dict[str, Any], dict[str, Any] | None, dict[str, Any] | None]:
    repo = resolve_path(args.repo)
    if not repo.is_dir():
        raise ScriptError(f"repo path does not exist: {repo}")
    out = resolve_path(args.out)
    artifact_dir = resolve_path(args.artifact_dir or out.parent)
    requirement = ensure_allowed_path(
        args.requirement,
        allowed_roots=[artifact_dir],
        allowed_files=[resolve_path(args.requirement)],
        purpose="requirement",
    )
    reject_benchmark_answer_path(requirement, purpose="requirement")
    index_path = ensure_allowed_path(args.index, allowed_roots=[repo, artifact_dir], purpose="index")
    out = ensure_allowed_path(out, allowed_roots=[repo, artifact_dir, out.parent], purpose="output")
    semantic_out = resolve_path(args.semantic_out or artifact_dir / "semantic-perception.json")
    semantic_out = ensure_allowed_path(
        semantic_out, allowed_roots=[repo, artifact_dir, semantic_out.parent], purpose="semantic-output"
    )
    semantic_markdown = resolve_path(args.semantic_markdown or artifact_dir / "semantic-perception.md")
    semantic_markdown = ensure_allowed_path(
        semantic_markdown,
        allowed_roots=[repo, artifact_dir, semantic_markdown.parent],
        purpose="semantic-markdown-output",
    )
    global_perception = None
    if args.global_perception:
        global_path = ensure_allowed_path(
            args.global_perception, allowed_roots=[repo, artifact_dir], purpose="global-perception"
        )
        global_perception = load_json(global_path)
        if global_perception.get("format") != FORMAT_GLOBAL:
            raise ScriptError(f"unsupported global perception format: {global_perception.get('format')}")
    repository_perception = None
    if args.repository_perception:
        repository_path = ensure_allowed_path(
            args.repository_perception, allowed_roots=[repo, artifact_dir], purpose="repository-perception"
        )
        repository_perception = load_json(repository_path)
        if repository_perception.get("format") != FORMAT_REPOSITORY:
            raise ScriptError(f"unsupported repository perception format: {repository_perception.get('format')}")
    requirement_text = read_text(requirement)
    index = load_json(index_path)
    if index.get("format") != FORMAT_INDEX:
        raise ScriptError(f"unsupported index format: {index.get('format')}")
    return (
        repo,
        requirement,
        index_path,
        out,
        semantic_out,
        semantic_markdown,
        artifact_dir,
        requirement_text,
        index,
        global_perception,
        repository_perception,
    )


def extract_requirement_signals(text: str) -> list[dict[str, Any]]:
    code_terms = re.findall(r"`([^`]{2,80})`", text)
    fenced_blocks = re.findall(r"```(?:\w+)?\n(.*?)```", text, flags=re.DOTALL)
    file_like = re.findall(
        r"[\w./-]+\.(?:py|java|scala|rs|c|h|cpp|hpp|toml|xml|gradle|rst|md|gram|asdl|g4|peg|y|l)",
        text,
        flags=re.IGNORECASE,
    )
    title_terms = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            title_terms.extend(tokenize(stripped))
    behavior_terms = tokenize(" ".join(fenced_blocks + code_terms + [text]), min_len=3)
    origins: dict[str, str] = {}
    for value in file_like:
        origins.setdefault(value.lower().strip(), "path_literal")
    for value in code_terms:
        origins.setdefault(value.lower().strip(), "code_literal")
    for value in title_terms:
        origins.setdefault(value.lower().strip(), "title")
    signals: list[dict[str, Any]] = []
    for term in stable_unique([*file_like, *code_terms, *title_terms, *behavior_terms])[:160]:
        lowered = str(term).lower().strip()
        if not lowered:
            continue
        signals.append(
            {
                "term": lowered,
                "category": categorize_signal(lowered),
                "source": "original_requirement",
                "origin": origins.get(lowered, "body"),
            }
        )
    return signals


def categorize_signal(term: str) -> str:
    if "/" in term or ("." in term and not term.endswith(".")):
        return "path"
    if term.startswith("--") or term in {"config", "option", "flag", "setting"}:
        return "config"
    if any(word in term for word in ("syntax", "grammar", "parser", "token", "expr", "statement")):
        return "syntax"
    if any(word in term for word in ("error", "exception", "invalid", "fail")):
        return "error"
    if any(word in term for word in ("test", "expected", "should")):
        return "test"
    if term[:1].isupper() or "_" in term or ":" in term:
        return "api"
    return "behavior"


def score_file(file_record: dict[str, Any], terms: set[str]) -> int:
    path = file_record.get("path", "").lower()
    record_terms = {str(item).lower() for item in file_record.get("terms", [])}
    symbol_terms = {term for symbol in file_record.get("symbols", []) for term in tokenize(symbol.get("name", ""))}
    preview = str(file_record.get("preview", "")).lower()
    score = 0
    for term in terms:
        variants = stable_unique([term, *path_tokens(term)])
        if any(path.endswith(variant) or path == variant for variant in variants):
            score += 15
        elif any(variant in path for variant in variants):
            score += 7
        if any(variant in record_terms for variant in variants):
            score += 5
        if any(variant in symbol_terms for variant in variants):
            score += 8
        if any(variant in preview for variant in variants):
            score += 2
    if file_record.get("kind") == "source":
        score += 2
    if file_record.get("is_test"):
        score -= 1
    return score


def rank_files(index: dict[str, Any], signals: list[dict[str, Any]], limit: int) -> list[dict[str, Any]]:
    terms = {signal["term"] for signal in signals}
    scored: list[tuple[int, str, dict[str, Any]]] = []
    for record in index.get("files", []):
        score = score_file(record, terms)
        if score <= 0:
            continue
        scored.append((score, record.get("path", ""), record))
    scored.sort(key=lambda item: (-item[0], item[1]))
    return [{**record, "score": score} for score, _, record in scored[:limit]]


def repo_map(index: dict[str, Any]) -> dict[str, Any]:
    files = index.get("files", [])
    top_levels: dict[str, dict[str, int]] = {}
    generated: list[str] = []
    build_files: list[str] = []
    test_roots: set[str] = set()
    for record in files:
        top = record.get("top_level") or "."
        bucket = top_levels.setdefault(top, {})
        kind = record.get("kind", "artifact")
        bucket[kind] = bucket.get(kind, 0) + 1
        if record.get("is_generated"):
            generated.append(record["path"])
        if kind == "build":
            build_files.append(record["path"])
        if record.get("is_test"):
            parts = Path(record["path"]).parts
            test_roots.add("/".join(parts[:2]) if len(parts) > 1 else record["path"])
    return {
        "top_levels": top_levels,
        "generated_files": generated[:40],
        "build_files": build_files[:40],
        "test_roots": sorted(test_roots)[:40],
        "stats": index.get("stats", {}),
    }


def infer_surfaces(
    index: dict[str, Any], signals: list[dict[str, Any]], ranked: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    terms = {signal["term"] for signal in signals}
    signal_categories = {signal["category"] for signal in signals}
    surfaces: list[dict[str, Any]] = []
    for name, rule in SURFACE_RULES.items():
        term_hit = bool(terms & rule["terms"])
        path_hits = [
            record
            for record in ranked
            if any(path_term in record.get("path", "").lower() for path_term in rule["path_terms"])
        ]
        category_hit = name == "syntax-parser" and "syntax" in signal_categories
        if not term_hit and not path_hits and not category_hit:
            continue
        confidence = "high" if (term_hit and path_hits) or (category_hit and path_hits) else "medium"
        surfaces.append(
            {
                "name": name,
                "why": surface_why(name, term_hit, bool(path_hits), category_hit),
                "inspect": [record["path"] for record in path_hits[:8]],
                "risk": rule["risk"],
                "confidence": confidence,
                "source": "code_evidence" if path_hits else "inferred",
                "evidence": [file_evidence(record) for record in path_hits[:5]],
            }
        )
    if not surfaces and ranked:
        surfaces.append(
            {
                "name": "repository-entry-points",
                "why": "Requirement terms matched repository files, but no specialized implementation surface was inferred.",
                "inspect": [record["path"] for record in ranked[:8]],
                "risk": "Verify these files with normal source inspection before editing.",
                "confidence": "medium",
                "source": "code_evidence",
                "evidence": [file_evidence(record) for record in ranked[:5]],
            }
        )
    return surfaces


def capability_requirements(
    requirement_text: str,
    signals: list[dict[str, Any]],
    index: dict[str, Any],
    surfaces: list[dict[str, Any]],
) -> dict[str, Any]:
    """Capture requirement-driven completeness hints that search cannot infer from existing files.

    This is deliberately conservative: these hints are not edit mandates, but they
    tell the final Augmented Requirement that missing/new files and generated or
    registration surfaces may be required even when current-repo search cannot rank
    them.
    """
    new_hints = new_or_missing_surface_hints(requirement_text, signals, index)
    chains = consistency_chains(requirement_text, signals, surfaces, bool(new_hints))
    limits: list[dict[str, str]] = []
    if new_hints:
        limits.append(
            {
                "claim": "Some required surfaces may not exist in the base checkout yet.",
                "source": "original_requirement",
                "confidence": "high",
                "action": "Do not assume semantic-search ranked files are complete; create or register missing modules/files only after source inspection confirms the Original Requirement requires them.",
            }
        )
    codegraph_summary = index.get("stats", {})
    if codegraph_summary:
        limits.append(
            {
                "claim": "Ranked evidence is based on files present in the current checkout.",
                "source": "code_evidence",
                "confidence": "high",
                "action": "Use ranked files as existing-context hints, not as a complete list of required edit surfaces for feature backports; preserve buildability and pass-to-pass behavior while choosing the final surface set.",
            }
        )
    return {
        "new_or_missing_surfaces": new_hints,
        "consistency_chains": chains,
        "localization_limits": limits,
    }


def new_or_missing_surface_hints(
    requirement_text: str, signals: list[dict[str, Any]], index: dict[str, Any]
) -> list[dict[str, str]]:
    hints: list[dict[str, str]] = []
    for signal in signals:
        term = str(signal.get("term", "")).strip()
        if not likely_named_surface(signal):
            continue
        if not requirement_context_indicates_surface(requirement_text, term, signal):
            continue
        if term_has_repo_match(term, index):
            continue
        hints.append(
            {
                "name": term,
                "kind": "new-or-missing-surface",
                "source": "original_requirement",
                "confidence": "medium",
                "action": "If this named API/module/file is required by the Original Requirement and is absent from the base checkout, verify the need in source first; then plan the minimal complete new surface rather than forcing the task into similar existing files.",
            }
        )
        if len(hints) >= 12:
            break
    return hints


def requirement_context_indicates_surface(requirement_text: str, term: str, signal: dict[str, Any]) -> bool:
    if signal.get("origin") == "path_literal":
        return True
    lowered = requirement_text.lower()
    escaped = re.escape(term.lower())
    first = lowered.find(term.lower())
    if signal.get("origin") == "code_literal" and (first < 0 or first > 2500):
        return False
    surface_cues = (
        "add",
        "adding",
        "introduce",
        "introduces",
        "new",
        "module",
        "package",
        "class",
        "function",
        "method",
        "api",
        "attribute",
        "parameter",
        "constructor",
        "flag",
        "option",
        "syntax",
        "grammar",
        "support for",
    )
    for match in re.finditer(escaped, lowered):
        start = max(0, match.start() - 90)
        end = min(len(lowered), match.end() + 90)
        window = lowered[start:end]
        if any(cue in window for cue in surface_cues):
            return True
    return False


def likely_named_surface(signal: dict[str, Any]) -> bool:
    term = str(signal.get("term", "")).strip().lower()
    if len(term) < 3 or len(term) > 64 or term in COMMON_PATH_TOKENS:
        return False
    if term.startswith(("http://", "https://")):
        return False
    if "." in term and not re.search(
        r"\.(?:py|java|scala|rs|c|h|cpp|hpp|toml|xml|gradle|rst|md|gram|asdl|g4|peg|y|l)$", term
    ):
        return False
    if "/" in term and "." not in term:
        return False
    origin = signal.get("origin")
    category = signal.get("category")
    if origin in {"code_literal", "path_literal"}:
        return bool(re.match(r"^[a-z_][a-z0-9_./-]*$", term))
    if category in {"syntax", "config", "path"}:
        return bool(re.match(r"^[a-z_][a-z0-9_./-]*$", term))
    return False


def term_has_repo_match(term: str, index: dict[str, Any]) -> bool:
    term = term.lower().strip()
    pieces = set(path_tokens(term)) | {term}
    pieces = {piece for piece in pieces if piece and piece not in COMMON_PATH_TOKENS}
    if not pieces:
        return True
    for record in index.get("files", []):
        path = str(record.get("path", "")).lower()
        path_piece_set = set(path_tokens(path))
        if term in path or pieces & path_piece_set:
            return True
        for symbol in record.get("symbols", [])[:40]:
            name = str(symbol.get("name", "")).lower()
            if term == name or term in path_tokens(name):
                return True
    return False


def consistency_chains(
    requirement_text: str,
    signals: list[dict[str, Any]],
    surfaces: list[dict[str, Any]],
    has_new_surfaces: bool,
) -> list[dict[str, str]]:
    text = requirement_text.lower()
    terms = {signal.get("term", "") for signal in signals}
    categories = {signal.get("category", "") for signal in signals}
    surface_names = {surface.get("name", "") for surface in surfaces}
    chains: list[dict[str, str]] = []
    if has_new_surfaces or any(
        word in text for word in ("add a module", "adding a module", "new module", "new package", "standard library")
    ):
        chains.append(
            {
                "name": "new-module-or-api-completeness",
                "source": "original_requirement",
                "confidence": "high" if has_new_surfaces else "medium",
                "action": "When the requirement introduces a module/API/class that does not exist yet, add the minimal source files plus only source-verified exports, build/install registration, metadata, and focused validation.",
            }
        )
    if (
        "syntax" in categories
        or "syntax-parser" in surface_names
        or any(term in terms for term in {"grammar", "parser", "asdl"})
    ):
        chains.append(
            {
                "name": "parser-generated-runtime-completeness",
                "source": "original_requirement + code_evidence",
                "confidence": "high",
                "action": "For syntax/parser/ASDL changes, identify the source-of-truth chain first; synchronize generated parser/AST artifacts, compiler/symtable/runtime consumers, and validation only when required, and preserve existing diagnostics and pass-to-pass behavior.",
            }
        )
    if "build-generated" in surface_names or any(
        word in text for word in ("generated", "regenerate", "configure", "makefile", "build")
    ):
        chains.append(
            {
                "name": "build-generated-registration-completeness",
                "source": "original_requirement + code_evidence",
                "confidence": "medium",
                "action": "If build/config/generated files are touched, preserve executable bits and file metadata, follow regeneration conventions, and include only required checked-in generated outputs or registration files.",
            }
        )
    return chains[:8]


def surface_why(name: str, term_hit: bool, path_hit: bool, category_hit: bool) -> str:
    reasons = []
    if term_hit:
        reasons.append("requirement terms match this surface")
    if path_hit:
        reasons.append("repository files match this surface")
    if category_hit:
        reasons.append("requirement examples indicate this surface")
    return f"{name} is relevant because " + ", ".join(reasons) + "."


def file_evidence(record: dict[str, Any]) -> dict[str, Any]:
    return {
        "path": record.get("path"),
        "kind": record.get("kind"),
        "language": record.get("language"),
        "score": record.get("score", 0),
        "symbols": [symbol.get("name") for symbol in record.get("symbols", [])[:5]],
    }


def file_detail(record: dict[str, Any]) -> dict[str, Any]:
    detail = file_evidence(record)
    detail.update(
        {
            "size": record.get("size", 0),
            "terms": record.get("terms", [])[:40],
            "symbols": record.get("symbols", [])[:12],
            "preview": str(record.get("preview", ""))[:1800],
        }
    )
    return detail


def existing_patterns(ranked: list[dict[str, Any]]) -> list[dict[str, Any]]:
    patterns: list[dict[str, Any]] = []
    for record in ranked[:12]:
        kind = record.get("kind", "file")
        if kind == "test":
            action = "Use this as a guide for expected behavior and narrow validation."
        elif record.get("is_generated"):
            action = "Treat this as generated or generation-adjacent; look for its source-of-truth before editing."
        elif kind in {"build", "config"}:
            action = "Check whether the feature needs registration, defaults, or generation commands here."
        else:
            action = "Inspect for local implementation style and nearby abstractions before editing."
        patterns.append(
            {
                "pattern": f"Relevant {kind} file: {record['path']}",
                "source": "code_evidence",
                "confidence": "medium",
                "evidence": file_evidence(record),
                "action": action,
            }
        )
    return patterns


def code_details(ranked: list[dict[str, Any]], symbol_limit: int) -> list[dict[str, Any]]:
    details: list[dict[str, Any]] = []
    for record in ranked:
        symbols = record.get("symbols", [])[: min(8, symbol_limit)]
        details.append(
            {
                "path": record["path"],
                "kind": record.get("kind"),
                "language": record.get("language"),
                "priority": "must inspect"
                if len(details) < 8 and record.get("kind") in {"source", "generated"}
                else "useful",
                "why": "Matched requirement signals or adjacent repository terms.",
                "confidence": "high" if record.get("score", 0) >= 20 else "medium",
                "symbols": symbols,
                "evidence": file_evidence(record),
            }
        )
        if len(details) >= 18:
            break
    return details


def validation_hints(
    index: dict[str, Any], ranked: list[dict[str, Any]], signals: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    hints: list[dict[str, Any]] = []
    seen: set[str] = set()
    for record in ranked:
        if not record.get("is_test"):
            continue
        path = record.get("path", "")
        if path in seen:
            continue
        seen.add(path)
        hints.append(
            {
                "kind": "narrow-test",
                "path": path,
                "source": "code_evidence",
                "confidence": "high" if record.get("score", 0) >= 20 else "medium",
                "action": "Inspect or run this ranked test only if it validates the touched behavior; prefer tests tied to the changed module or public API.",
                "matched_terms": [token for token in path_tokens(path) if token not in GENERIC_VALIDATION_TOKENS][:8],
            }
        )
        if len(hints) >= 12:
            break
    ranked_terms = {
        token
        for record in ranked[:8]
        for token in path_tokens(record.get("path", ""))
        if token not in GENERIC_VALIDATION_TOKENS
    }
    for record in index.get("files", []):
        if not record.get("is_test"):
            continue
        path = record.get("path", "")
        if path in seen:
            continue
        tokens = {token for token in path_tokens(path) if token not in GENERIC_VALIDATION_TOKENS}
        overlap = tokens & ranked_terms
        if len(overlap) >= 2:
            seen.add(path)
            hints.append(
                {
                    "kind": "narrow-test",
                    "path": path,
                    "source": "code_evidence",
                    "confidence": "medium",
                    "action": "Inspect or run this only if it validates the touched behavior; prefer tests tied to the changed module or public API.",
                    "matched_terms": sorted(overlap)[:8],
                }
            )
        if len(hints) >= 12:
            break
    for record in index.get("files", []):
        if record.get("kind") == "build" and Path(record.get("path", "")).name in IMPORTANT_BUILD_NAMES:
            hints.append(
                {
                    "kind": "build-entry",
                    "path": record["path"],
                    "source": "code_evidence",
                    "confidence": "medium",
                    "action": "Check this build/config entry only if source changes require generation or registration; preserve executable bits, file metadata, and buildability if it is touched.",
                }
            )
        if len(hints) >= 18:
            break
    return hints


def anti_patterns(surfaces: list[dict[str, Any]]) -> list[dict[str, Any]]:
    base = [
        "Do not replace source inspection with this plan; verify named files and functions before editing.",
        "Do not edit tests or generated artifacts as a substitute for implementing source behavior.",
        "Do not hard-code examples from the requirement; implement the general behavior.",
        "Do not ignore existing behavior; preserve pass-to-pass compatibility.",
    ]
    generated = any(surface["name"] == "build-generated" for surface in surfaces)
    parser = any(surface["name"] == "syntax-parser" for surface in surfaces)
    if generated or parser:
        base.append(
            "Do not change a source-of-truth grammar/token/schema without checking generated or registered artifacts."
        )
        base.append(
            "Do not let generated/build synchronization change executable bits, file metadata, diagnostics, or pass-to-pass behavior unless the requirement explicitly needs it."
        )
    if any(surface["name"] == "new-or-missing-surface" for surface in surfaces):
        base.append(
            "Do not force a required new module/API into unrelated existing files just because current-repo search found similar names."
        )
    return [
        {"claim": item, "source": "inferred", "confidence": "medium", "action": "Use as a pre-final checklist."}
        for item in base
    ]


def uncertainties(surfaces: list[dict[str, Any]], ranked: list[dict[str, Any]]) -> list[dict[str, Any]]:
    items = []
    for surface in surfaces:
        if surface.get("confidence") != "high":
            items.append(
                {
                    "question": f"Confirm whether the {surface['name']} surface is actually required.",
                    "source": surface.get("source", "inferred"),
                    "confidence": "low",
                    "evidence": surface.get("evidence", []),
                }
            )
    if not ranked:
        items.append(
            {
                "question": "Requirement terms did not strongly match indexed repository files; start with normal repository exploration.",
                "source": "uncertain",
                "confidence": "low",
                "evidence": [],
            }
        )
    return items[:12]


def compact_global_perception(global_perception: dict[str, Any] | None) -> dict[str, Any]:
    if not global_perception:
        return {}
    return {
        "backend": global_perception.get("backend", ""),
        "overview": global_perception.get("overview", {}),
        "module_clusters": global_perception.get("module_clusters", [])[:16],
        "entrypoints": global_perception.get("entrypoints", [])[:24],
        "dependency_hints": global_perception.get("dependency_hints", [])[:40],
        "topology": global_perception.get("topology", {}),
        "source_of_truth_hints": global_perception.get("source_of_truth_hints", [])[:40],
        "external_graph_summary": global_perception.get("external_graph_summary", {}),
        "global_risks": global_perception.get("global_risks", []),
    }


def compact_repository_perception(repository_perception: dict[str, Any] | None) -> dict[str, Any]:
    if not repository_perception:
        return {}
    codegraph_layer = repository_perception.get("codegraph_layer", {})
    return {
        "backend": repository_perception.get("backend", ""),
        "overview": repository_perception.get("overview", {}),
        "module_map": dict(list(repository_perception.get("module_map", {}).items())[:24]),
        "global_layer": {
            "entrypoints": repository_perception.get("global_layer", {}).get("entrypoints", [])[:24],
            "dependency_hints": repository_perception.get("global_layer", {}).get("dependency_hints", [])[:40],
            "module_clusters": repository_perception.get("global_layer", {}).get("module_clusters", [])[:16],
        },
        "codegraph_layer": {
            "available": codegraph_layer.get("available", False),
            "status": codegraph_layer.get("status", ""),
            "summary": codegraph_layer.get("summary", {}),
            "query_evidence": codegraph_layer.get("query_evidence", [])[:8],
            "relationship_evidence": codegraph_layer.get("relationship_evidence", [])[:8],
            "notes": codegraph_layer.get("notes", [])[:8],
        },
        "source_of_truth": repository_perception.get("source_of_truth", {}),
        "validation_surface": repository_perception.get("validation_surface", {}),
        "risks": repository_perception.get("risks", [])[:16],
    }


def global_semantic_links(
    signals: list[dict[str, Any]],
    ranked: list[dict[str, Any]],
    surfaces: list[dict[str, Any]],
    global_perception: dict[str, Any] | None,
) -> list[dict[str, Any]]:
    if not global_perception:
        return []
    signal_terms = {term for signal in signals for term in path_tokens(signal.get("term", ""))}
    ranked_paths = {record.get("path", "") for record in ranked}
    links: list[dict[str, Any]] = []
    for cluster in global_perception.get("module_clusters", [])[:24]:
        cluster_text = " ".join(
            [
                str(cluster.get("name", "")),
                " ".join(cluster.get("representative_files", [])),
                " ".join(
                    symbol.get("name", "")
                    for symbol in cluster.get("representative_symbols", [])
                    if isinstance(symbol, dict)
                ),
            ]
        ).lower()
        overlap = sorted(term for term in signal_terms if term and term in cluster_text)[:12]
        ranked_overlap = [path for path in cluster.get("representative_files", []) if path in ranked_paths][:6]
        if not overlap and not ranked_overlap:
            continue
        links.append(
            {
                "kind": "global-cluster-match",
                "cluster": cluster.get("name"),
                "source": "code_evidence",
                "confidence": "medium" if overlap else "low",
                "why": "Requirement signals or ranked task files intersect this global module cluster.",
                "signals": overlap,
                "ranked_files": ranked_overlap,
                "action": "Inspect this cluster as surrounding context before deciding edit scope.",
            }
        )
    surface_terms = {term for surface in surfaces for term in path_tokens(surface.get("name", ""))}
    for entry in global_perception.get("entrypoints", [])[:30]:
        entry_text = f"{entry.get('path', '')} {entry.get('reason', '')}".lower()
        overlap = sorted(term for term in signal_terms | surface_terms if term and term in entry_text)[:12]
        if not overlap:
            continue
        links.append(
            {
                "kind": "entrypoint-match",
                "path": entry.get("path"),
                "source": "code_evidence",
                "confidence": "medium",
                "why": "Task signals intersect a global entrypoint or core surface.",
                "signals": overlap,
                "action": "Check whether the task needs registration, integration, or source-of-truth updates through this entrypoint.",
            }
        )
    return links[:24]


def semantic_perception_payload(
    requirement: Path,
    index_path: Path,
    facts: dict[str, Any],
    global_perception: dict[str, Any] | None,
    repository_perception: dict[str, Any] | None,
    global_links: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "format": "semantic-search-task-perception",
        "created_at": now_iso(),
        "inputs": {
            "requirement": str(requirement),
            "requirement_sha1": sha1_path(requirement),
            "index": str(index_path),
            "index_sha1": sha1_path(index_path),
        },
        "requirement_signals": facts["requirement_signals"],
        "ranked_files": facts["ranked_files"],
        "ranked_file_details": facts["ranked_file_details"],
        "capability_requirements": facts.get("capability_requirements", {}),
        "implementation_surfaces": facts["implementation_surfaces"],
        "existing_patterns": facts["existing_patterns"],
        "validation_hints": facts["validation_hints"],
        "anti_patterns": facts["anti_patterns"],
        "uncertainties": facts["uncertainties"],
        "global_semantic_links": global_links,
        "global_perception_available": bool(global_perception),
        "repository_perception_available": bool(repository_perception),
        "codegraph_available": bool((repository_perception or {}).get("codegraph_layer", {}).get("available")),
    }


def render_semantic_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Semantic Task Perception",
        "",
        "This document links the Original Requirement signals to task-specific code evidence and global codebase perception.",
        "",
        "## Requirement Signals",
        "",
    ]
    lines.extend(
        bullet_lines(
            [
                f"`{item.get('term', '')}` ({item.get('category', '')}, source={item.get('source', '')})"
                for item in payload.get("requirement_signals", [])[:80]
            ]
        )
    )
    lines.extend(["", "## Ranked Task Evidence", ""])
    for item in payload.get("ranked_file_details", [])[:12]:
        lines.append(
            f"- `{item.get('path', '')}` ({item.get('kind', '')}/{item.get('language', '')}, score={item.get('score', 0)})"
        )
        symbols = ", ".join(
            symbol.get("name", "") for symbol in item.get("symbols", [])[:6] if isinstance(symbol, dict)
        )
        if symbols:
            lines.append(f"  Symbols: {symbols}")
    lines.extend(["", "## Implementation Surfaces", ""])
    for surface in payload.get("implementation_surfaces", []):
        lines.append(f"- `{surface.get('name', '')}`")
        lines.append(f"  Source: {surface.get('source', '')}")
        lines.append(f"  Confidence: {surface.get('confidence', '')}")
        lines.append(f"  Why: {surface.get('why', '')}")
        lines.append(f"  Inspect: {', '.join(f'`{path}`' for path in surface.get('inspect', [])[:8]) or '(none)'}")
        lines.append(f"  Risk: {surface.get('risk', '')}")
    lines.extend(["", "## Global/Semantic Links", ""])
    for link in payload.get("global_semantic_links", []):
        target = link.get("cluster") or link.get("path") or "(unknown)"
        lines.append(f"- `{target}` ({link.get('kind', '')})")
        lines.append(f"  Source: {link.get('source', '')}")
        lines.append(f"  Confidence: {link.get('confidence', '')}")
        lines.append(f"  Why: {link.get('why', '')}")
        lines.append(f"  Action: {link.get('action', '')}")
    capabilities = payload.get("capability_requirements", {})
    lines.extend(["", "## New or Missing Surface Hints", ""])
    for item in capabilities.get("new_or_missing_surfaces", [])[:12]:
        lines.append(f"- `{item.get('name', '')}` ({item.get('kind', '')})")
        lines.append(f"  Source: {item.get('source', '')}")
        lines.append(f"  Confidence: {item.get('confidence', '')}")
        lines.append(f"  Action: {item.get('action', '')}")
    lines.extend(["", "## Required Consistency Chains", ""])
    for item in capabilities.get("consistency_chains", [])[:8]:
        lines.append(f"- `{item.get('name', '')}`")
        lines.append(f"  Source: {item.get('source', '')}")
        lines.append(f"  Confidence: {item.get('confidence', '')}")
        lines.append(f"  Action: {item.get('action', '')}")
    lines.extend(["", "## Validation Hints", ""])
    for hint in payload.get("validation_hints", [])[:18]:
        lines.append(f"- `{hint.get('path', '')}` ({hint.get('kind', '')})")
        lines.append(f"  Source: {hint.get('source', '')}")
        lines.append(f"  Confidence: {hint.get('confidence', '')}")
        lines.append(f"  Action: {hint.get('action', '')}")
    lines.extend(["", "## Uncertainties", ""])
    lines.extend(bullet_lines([item.get("question", "") for item in payload.get("uncertainties", [])]))
    return "\n".join(lines).rstrip() + "\n"


def build_facts(args: argparse.Namespace) -> dict[str, Any]:
    (
        repo,
        requirement,
        index_path,
        out,
        semantic_out,
        semantic_markdown,
        _artifact_dir,
        requirement_text,
        index,
        global_perception,
        repository_perception,
    ) = load_inputs(args)
    signals = extract_requirement_signals(requirement_text)
    ranked = rank_files(index, signals, args.top_files)
    surfaces = infer_surfaces(index, signals, ranked)
    capabilities = capability_requirements(requirement_text, signals, index, surfaces)
    if capabilities.get("new_or_missing_surfaces"):
        surfaces.insert(
            0,
            {
                "name": "new-or-missing-surface",
                "why": "The Original Requirement names APIs, modules, syntax, or files that may not exist in the base checkout.",
                "inspect": [],
                "risk": "Current-repo semantic search cannot rank files that do not exist yet; over-relying on similar existing files can omit required new source, registration, or generated outputs.",
                "confidence": "medium",
                "source": "original_requirement",
                "evidence": capabilities.get("new_or_missing_surfaces", [])[:5],
            },
        )
    repo_summary = repo_map(index)
    compact_global = compact_global_perception(global_perception)
    compact_repository = compact_repository_perception(repository_perception)
    global_links = global_semantic_links(signals, ranked, surfaces, global_perception)
    ranked_files = [file_evidence(record) for record in ranked]
    ranked_file_details = [file_detail(record) for record in ranked[:12]]
    patterns = existing_patterns(ranked)
    details = code_details(ranked, args.top_symbols)
    validation = validation_hints(index, ranked, signals)
    risks = anti_patterns(surfaces)
    open_items = uncertainties(surfaces, ranked)
    general_code_facts = {
        "repo_map": repo_summary,
        "capability_requirements": capabilities,
        "repository_perception": compact_repository,
        "global_perception": compact_global,
        "index_stats": index.get("stats", {}),
        "top_levels": repo_summary.get("top_levels", {}),
        "generated_files": repo_summary.get("generated_files", []),
        "build_files": repo_summary.get("build_files", []),
        "test_roots": repo_summary.get("test_roots", []),
        "source_of_truth_hints": compact_global.get("source_of_truth_hints", []),
        "global_risks": compact_global.get("global_risks", []),
    }
    semantic_search_facts = {
        "requirement_signals": signals,
        "ranked_files": ranked_files,
        "ranked_file_details": ranked_file_details,
        "capability_requirements": capabilities,
        "implementation_surfaces": surfaces,
        "existing_patterns": patterns,
        "code_details": details,
        "validation_hints": validation,
        "anti_patterns": risks,
        "uncertainties": open_items,
        "global_semantic_links": global_links,
    }
    facts = {
        "format": FORMAT_FACTS,
        "created_at": now_iso(),
        "inputs": {
            "repo": str(repo),
            "requirement": str(requirement),
            "requirement_sha1": sha1_path(requirement),
            "index": str(index_path),
            "index_sha1": sha1_path(index_path),
        },
        "general_code_facts": general_code_facts,
        "semantic_search_facts": semantic_search_facts,
        # Backward-compatible aliases for existing augmentation/rendering code.
        "requirement_signals": signals,
        "repo_map": repo_summary,
        "repository_perception": compact_repository,
        "global_perception": compact_global,
        "ranked_files": ranked_files,
        "ranked_file_details": ranked_file_details,
        "capability_requirements": capabilities,
        "implementation_surfaces": surfaces,
        "existing_patterns": patterns,
        "code_details": details,
        "validation_hints": validation,
        "anti_patterns": risks,
        "uncertainties": open_items,
        "global_semantic_links": global_links,
        "augmentation_routes": [],
    }
    write_json(out, facts)
    semantic_payload = semantic_perception_payload(
        requirement, index_path, facts, global_perception, repository_perception, global_links
    )
    write_json(semantic_out, semantic_payload)
    semantic_markdown.write_text(render_semantic_markdown(semantic_payload), encoding="utf-8")
    write_json(
        out.parent / "repo-map.json",
        {
            "format": "semantic-search-repo-map",
            "created_at": now_iso(),
            "inputs": facts["inputs"],
            "repo_map": repo_summary,
        },
    )
    append_trace(
        "mine-context",
        {
            "out": str(out),
            "semantic_out": str(semantic_out),
            "surface_count": len(surfaces),
            "ranked_file_count": len(ranked),
            "global_links": len(global_links),
        },
    )
    return facts


def main(argv: list[str]) -> int:
    try:
        args = parse_args(argv)
        facts = build_facts(args)
        print(f"Wrote semantic-search code facts: {resolve_path(args.out)}")
        print({"surfaces": len(facts["implementation_surfaces"]), "ranked_files": len(facts["ranked_files"])})
        return 0
    except ScriptError as err:
        print(f"Error: {err}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
