# Copyright (c) 2026 Chrys. All rights reserved.

"""Chrys-owned agent kernel.

P5.1 ships the middleware foundation (``middleware.py``); P5.2 adds the tool
loop (``loop.py``); P5.3 adds the agent orchestrator (``agent.py``); P5.4 adds
the session/context/history layer (``sessions.py``); P5.5 adds the telemetry
layers (``instrumentation.py``); P5.6 adds the compaction primitives
(``compaction.py``); N3 adds the public-type façade (``types.py``) — the
single chokepoint through which the rest of chrys imports kernel types;
N5 adds the chrys-owned ``FunctionTool`` invoke/construction surface
(``tools.py``), which the façade serves in place of the framework originals.

HARD RULE: modules in this package import only the stdlib, intra-package
modules, the allowed third-party packages, and downward ``chrys.foundation.*``
modules — never sibling or upward ``chrys.{kernel,service,orchestration,app}``
modules. ``chrys.service.agent_middleware`` imports this package, so any
reverse import is a cycle. Intra-package references use *relative* imports so
the rule stays mechanically checkable as
``rg -n '^(from|import) chrys\\.' src/chrys/kernel | rg -v 'chrys\\.foundation\\.'``
with zero exceptions.
"""

from chrys.foundation.observability.gate import TELEMETRY_GATE, configure_telemetry

from .agent import Agent
from .client import (
    CONVERSATION_HANDLE_KEYS,
    BaseChatClient,
    StorageModeResolution,
    collect_conversation_handles,
    resolve_storage_mode_and_handles,
    strip_invalidated_conversation_handles,
)
from .compaction import (
    EXCLUDE_REASON_KEY,
    EXCLUDED_KEY,
    GROUP_ANNOTATION_KEY,
    GROUP_ID_KEY,
    GROUP_KIND_KEY,
    SUMMARIZED_BY_SUMMARY_ID_KEY,
    SUMMARY_OF_GROUP_IDS_KEY,
    SUMMARY_OF_MESSAGE_IDS_KEY,
    TOOL_CALL_CONTENT_TYPES,
    TOOL_RESULT_CONTENT_TYPES,
    CompactionAdmissionState,
    CompactionCallContext,
    CompactionProjectionAtomicityError,
    CompactionStrategy,
    GroupKind,
    LastWordsCompleter,
    LastWordsToolCallError,
    TokenizerProtocol,
    annotate_message_groups,
    annotate_token_counts,
    apply_compaction,
    estimate_message_tokens,
    exclude_group_ids,
    in_internal_side_call,
    included_messages,
    included_token_count,
    internal_side_call_scope,
    messages_contain_tool_calls,
    project_included_messages,
    set_excluded,
)
from .images import is_image_content, is_image_media_type
from .instrumentation import (
    AgentTelemetryLayer,
    ChatTelemetryLayer,
)
from .loop import LoopRecorder, StallExhaustedAction, ToolLoopLayer, WireRetryPolicy
from .middleware import (
    ChatContext,
    ChatMiddleware,
    ChatMiddlewareLayer,
    ChatMiddlewarePipeline,
    FunctionInvocationContext,
    FunctionMiddleware,
    FunctionMiddlewarePipeline,
    MiddlewareSplit,
    MiddlewareTermination,
    SupportsGetResponse,
    split_middleware,
)
from .sessions import (
    LOCAL_HISTORY_CONVERSATION_ID,
    AgentSession,
    ContextProvider,
    HistoryProvider,
    InMemoryHistoryProvider,
    ServiceFallbackHistoryProvider,
    SessionContext,
    is_local_history_conversation_id,
)
from .types import (
    RETRY_BOUNDARY_UPDATE_KEY,
    SKIP_PARSING,
    AdditionItemMismatch,
    AgentInvalidResponseException,
    AgentResponse,
    AgentResponseUpdate,
    AgentRunInputs,
    Annotation,
    ChatClientContentFilterException,
    ChatClientException,
    ChatClientInvalidRequestException,
    ChatOptions,
    ChatResponse,
    ChatResponseUpdate,
    Content,
    ContentError,
    ContinuationToken,
    FinishReason,
    FinishReasonLiteral,
    FunctionInvocationConfiguration,
    FunctionTool,
    Message,
    ResponseStream,
    Role,
    TextSpanRegion,
    ToolException,
    ToolTypes,
    UsageDetails,
    add_usage_details,
    detect_media_type_from_base64,
    is_retry_boundary_update,
    map_chat_to_agent_update,
    merge_chat_options,
    normalize_messages,
    normalize_stream_usage,
    normalize_tools,
    prepend_instructions_to_messages,
    tool,
    validate_chat_options,
    validate_tool_mode,
)

__all__ = [
    "CONVERSATION_HANDLE_KEYS",
    "EXCLUDED_KEY",
    "EXCLUDE_REASON_KEY",
    "GROUP_ANNOTATION_KEY",
    "GROUP_ID_KEY",
    "GROUP_KIND_KEY",
    "LOCAL_HISTORY_CONVERSATION_ID",
    "RETRY_BOUNDARY_UPDATE_KEY",
    "SKIP_PARSING",
    "SUMMARIZED_BY_SUMMARY_ID_KEY",
    "SUMMARY_OF_GROUP_IDS_KEY",
    "SUMMARY_OF_MESSAGE_IDS_KEY",
    "TELEMETRY_GATE",
    "TOOL_CALL_CONTENT_TYPES",
    "TOOL_RESULT_CONTENT_TYPES",
    "AdditionItemMismatch",
    "Agent",
    "AgentInvalidResponseException",
    "AgentResponse",
    "AgentResponseUpdate",
    "AgentRunInputs",
    "AgentSession",
    "AgentTelemetryLayer",
    "Annotation",
    "BaseChatClient",
    "ChatClientContentFilterException",
    "ChatClientException",
    "ChatClientInvalidRequestException",
    "ChatContext",
    "ChatMiddleware",
    "ChatMiddlewareLayer",
    "ChatMiddlewarePipeline",
    "ChatOptions",
    "ChatResponse",
    "ChatResponseUpdate",
    "ChatTelemetryLayer",
    "CompactionAdmissionState",
    "CompactionCallContext",
    "CompactionProjectionAtomicityError",
    "CompactionStrategy",
    "Content",
    "ContentError",
    "ContextProvider",
    "ContinuationToken",
    "FinishReason",
    "FinishReasonLiteral",
    "FunctionInvocationConfiguration",
    "FunctionInvocationContext",
    "FunctionMiddleware",
    "FunctionMiddlewarePipeline",
    "FunctionTool",
    "GroupKind",
    "HistoryProvider",
    "InMemoryHistoryProvider",
    "LastWordsCompleter",
    "LastWordsToolCallError",
    "LoopRecorder",
    "Message",
    "MiddlewareSplit",
    "MiddlewareTermination",
    "ResponseStream",
    "Role",
    "ServiceFallbackHistoryProvider",
    "SessionContext",
    "StallExhaustedAction",
    "StorageModeResolution",
    "SupportsGetResponse",
    "TextSpanRegion",
    "TokenizerProtocol",
    "ToolException",
    "ToolLoopLayer",
    "ToolTypes",
    "UsageDetails",
    "WireRetryPolicy",
    "add_usage_details",
    "annotate_message_groups",
    "annotate_token_counts",
    "apply_compaction",
    "collect_conversation_handles",
    "configure_telemetry",
    "detect_media_type_from_base64",
    "estimate_message_tokens",
    "exclude_group_ids",
    "in_internal_side_call",
    "included_messages",
    "included_token_count",
    "internal_side_call_scope",
    "is_image_content",
    "is_image_media_type",
    "is_local_history_conversation_id",
    "is_retry_boundary_update",
    "map_chat_to_agent_update",
    "merge_chat_options",
    "messages_contain_tool_calls",
    "normalize_messages",
    "normalize_stream_usage",
    "normalize_tools",
    "prepend_instructions_to_messages",
    "project_included_messages",
    "resolve_storage_mode_and_handles",
    "set_excluded",
    "split_middleware",
    "strip_invalidated_conversation_handles",
    "tool",
    "validate_chat_options",
    "validate_tool_mode",
]
